- alias: Turn lights off at sunrise
  trigger:
   platform: sun
   event: sunrise
   offset: '+00:45:00'
  action:
   service: homeassistant.turn_off
   entity_id: group.outdoor_lights, group.indoor_lights
   
