- alias: Back Door open turn barn light on
  id: 1ecb87a2-8006-46a1-ad3f-66239cdd6755
  trigger:
    - platform: state
      entity_id: binary_sensor.wink_back_door_opened, binary_sensor.garage_entry_door
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.wink_back_door_opened, binary_sensor.garage_entry_door
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: switch.ahr_085_2_relay2
      state: 'off'
    - condition: state
      entity_id: binary_sensor.still_dark
      state: 'on'
    - condition: state
      entity_id: input_boolean.fox_hunt
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.ahr_085_2_relay2