- alias: Back Door open turn barn light on
  trigger:
    - platform: state
      entity_id: binary_sensor.wink_back_door_opened, binary_sensor.wink_garage_entry_opened
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.wink_back_door_opened, binary_sensor.wink_garage_entry_opened
      from: 'on'
      to: 'off'
  condition:
     - condition: state
       entity_id: sun.sun
       state: 'below_horizon'
     - condition: state
       entity_id: switch.esp5
       state: 'off'
     - condition: state
       entity_id: binary_sensor.still_dark
       state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.esp5