- alias: Basement door open and light is already on via door open keep light on for another 10.
  trigger:
    - platform: state
      entity_id: binary_sensor.basement_door
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.basement_door
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.wink_md1_motion
      from: 'off'
      to: 'on'
  condition:
#     - condition: state
#       entity_id: sun.sun
#       state: 'below_horizon'
#    - condition: state
#      entity_id: script.timer_basement_off
#      state: 'on'
#     - condition: state
#       entity_id: binary_sensor.still_dark
#       state: 'on'
    - condition: state
      entity_id: timer.basement_light
      state: 'active'
  action:
#     - service: homeassistant.turn_off
#       entity_id: script.timer_basement_off
#     - service: homeassistant.turn_on
#       entity_id: script.timer_basement_off
    - service: timer.start
      entity_id: timer.basement_light
      data:
        duration: '00:10:00'




- alias: Basement door open turn basement_light on for 10 minutes unless it is already on.
  trigger:
    - platform: state
      entity_id: binary_sensor.basement_door
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.basement_door
      from: 'on'
      to: 'off'
  condition:
#     - condition: state
#       entity_id: sun.sun
#       state: 'below_horizon'
     - condition: state
       entity_id: switch.wink_basement
       state: 'off'
#     - condition: state
#       entity_id: binary_sensor.still_dark
#       state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.wink_basement
    - service: timer.start
      entity_id: timer.basement_light
      data:
        duration: '00:10:00'