- alias: Bed time but garage is still open
  trigger:
    - platform: event
      event_type: ac:63:be:91:20:72
  condition:
   condition: state
   entity_id: group.garage
   state: 'open'
  action:
    - service: notify.ios_group
      data_template:
        title: 'Garage open at bedtime'
        message: >
            "Garage is still open"
    - service: homeassistant.turn_on
      entity_id: light.wink_hallway
    - delay: '00:00:05'
    - service: homeassistant.turn_off
      entity_id: light.wink_hallway
    - delay: '00:00:05'
    - service: homeassistant.turn_on
      entity_id: light.wink_hallway
    - delay: '00:00:05'
    - service: homeassistant.turn_off
      entity_id: light.wink_hallway
    - delay: '00:00:05'
    - service: homeassistant.turn_on
      entity_id: light.wink_hallway
    - delay: '00:00:05'
    - service: homeassistant.turn_off
      entity_id: light.wink_hallway
    - delay: '00:00:05'
    - service: homeassistant.turn_on
      entity_id: light.wink_hallway
    - delay: '00:00:05'
    - service: homeassistant.turn_off
      entity_id: light.wink_hallway
    - delay: '00:00:05'
    - service: homeassistant.turn_on
      entity_id: light.wink_hallway
    - delay: '00:00:05'
    - service: homeassistant.turn_off
      entity_id: light.wink_hallway
    - delay: '00:00:05'
    - service: homeassistant.turn_on
      entity_id: light.wink_hallway
    - delay: '00:00:05'
    - service: homeassistant.turn_off
      entity_id: light.wink_hallway
    - delay: '00:00:05'
