- alias: Camper - temp
  id: ff3636c4-49d1-4088-a92d-5642c7292f6f
#  initial_state: false
  trigger:
   - platform: numeric_state
     entity_id: sensor.camper_temp
     above: 80.1
     for:
       minutes: 1
   - platform: numeric_state
     entity_id: sensor.camper_temp
     below: 80.0
     for:
       minutes: 1
#  action:
#    service: >
#      {% if (states.sensor.camper_temp.state ) >= '80' %}
#      homeassistant.turn_on
#      {% else %}
#      homeassistant.turn_off
#      {% endif %}
#    entity_id:
#      - switch.esp3
  action:
   -  service: notify.telegram_group
      data:
        title: 'Camper'
        message: >
          {{ trigger.to_state.name }} is {{ trigger.to_state.state }} and {{states.sensor.camper_humid.state}} humidity 

