- alias: Chicken - Turn off chicken coop door switch after 13 seconds
  initial_state: true
  trigger:
   platform: state
   entity_id: switch.sensornode2_relay2
   to: 'on'
   for:
     seconds: 13
  action:
    - service: homeassistant.turn_off
      entity_id: switch.sensornode2_relay2
      
- alias: Chicken - Turn off chicken pen door switch after 13 seconds
  initial_state: true
  trigger:
   platform: state
   entity_id: switch.sensornode2_relay1
   to: 'on'
   for:
     seconds: 13
  action:
    - service: homeassistant.turn_off
      entity_id: switch.sensornode2_relay1
          
          
- alias: Chicken -  Send Message on chicken state changes
  initial_state: true
  trigger:
    - platform: state
      entity_id: cover.chicken_door
      from: "open"
      to: "closed"
    - platform: state
      entity_id: cover.chicken_door
      from: "closed"
      to: "open"
  condition:
    - condition: state
      entity_id: input_boolean.chicken_door_automations
      state: 'off'
  action:
   -  service: notify.ios_group
      data:
 #       title: '{{ "\ud83d\udc14" }}Chicken Coop{{ "\ud83d\udc14" }}'
        title: "\U0001F414 Chicken Coop \U0001F414" 
 
        message: >
          {{ trigger.to_state.name }} is {{ trigger.to_state.state }}
        data:
          push:
           category: 'chicken_door'
           
           
- alias: Chicken -  Chicken Door Timer V2
  initial_state: true
  trigger:
    - platform: template
      value_template: '{{ states.sensor.time.state == states.sensor.chicken_door_open_time_dirty.state }}'
#    - platform: state
#      entity_id: sun.sun
#      to: 'above_horizon'
  condition:
    - condition: state
      entity_id: input_boolean.chicken_door
      state: 'on'
    - condition: state
      entity_id: cover.chicken_door
      state: 'closed'
#    - condition: state
#     entity_id: sun.sun
#     state: 'above_horizon'
    - condition: template
      value_template: '{{ states.sensor.time.state >= states.sensor.chicken_door_open_time_dirty.state }}'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.chicken_door_automations, automation.chicken_door_last_call_v2
    - service: homeassistant.turn_off
      entity_id: automation.chicken_coop_door_lockout, input_boolean.cancel_last_call
    - service: cover.open_cover
      entity_id: cover.chicken_door
    - wait_template: "{{ is_state('cover.chicken_door', 'open') }}"
      timeout: 00:00:15
    - service: notify.telegram_group
      data:
        title: "\U0001F414 Chicken Door Trigger \U0001F414"
        message: >
          {% if is_state('cover.chicken_door', 'open') %}
            Success: Automation triggered the door to open and it did.
          {% else %}
            Failure: Automation triggered the door to open but it did not!
          {% endif %}
        data:
          inline_keyboard:
           - 'Open Door:/CHICKEN_OPEN_DOOR'
           - 'Close Door:/CHICKEN_CLOSE_DOOR'
    - service: homeassistant.turn_off
      entity_id: input_boolean.chicken_door_automations, input_boolean.chicken_door_last_call
      

- alias: Chicken - Sunset close door V2
  initial_state: true
  trigger:
    - platform: template
      value_template: '{{ states.sensor.time.state == states.sensor.chicken_door_close_time_dirty.state }}'
  condition:
    - condition: state
      entity_id: cover.chicken_door
      state: 'open'
    - condition: template
      value_template: '{{ states.sensor.time.state >= states.sensor.chicken_door_close_time_dirty.state }}'
    - condition: state
      entity_id: input_boolean.chicken_door_last_call
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.chicken_door_automations
    - service: homeassistant.turn_off
      entity_id: automation.chicken_coop_door_lockout
    - service: cover.close_cover
      entity_id: cover.chicken_door
    - wait_template: "{{ is_state('cover.chicken_door', 'closed') }}"
      timeout: 00:00:15
    - service: notify.telegram_group
      data:
        title: "\U0001F414 Chicken Door Closed \U0001F414"
        message: >
          {% if is_state('cover.chicken_door', 'closed') %}
            Automation triggered the door to close and it did.
          {% else %}
            Automation triggered the door to close but it did not!
          {% endif %}
        data:
          inline_keyboard:
           - 'Open Door:/CHICKEN_OPEN_DOOR'
           - 'Close Door:/CHICKEN_CLOSE_DOOR'
    - service: homeassistant.turn_off
      entity_id: input_boolean.chicken_door_automations

- alias: Chicken - Door - Last Call V2
  initial_state: true
  trigger:
    - platform: template
      value_template: '{{ states.sensor.time.state == states.sensor.chicken_door_last_call_time_dirty.state }}'
  condition:
    - condition: state
      entity_id: cover.chicken_door
      state: 'closed'
    - condition: state
      entity_id: input_boolean.cancel_last_call
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.chicken_door_last_call, input_boolean.chicken_door_automations
    - service: cover.open_cover
      entity_id: cover.chicken_door
    - wait_template: "{{ is_state('cover.chicken_door', 'open') }}"
      timeout: 00:00:15
    - service: notify.telegram_group
      data:
        title: "\U0001F414 Last Call - Chicken Door \U0001F414"
        message: >
          {% if is_state('cover.chicken_door', 'open') %}
            I opened the chicken door for last call.
          {% else %}
            I tried to open the chicken door for last call but it did not open!
          {% endif %}
        data:
          inline_keyboard:
           - 'Open Door:/CHICKEN_OPEN_DOOR'
           - 'Close Door:/CHICKEN_CLOSE_DOOR'
    - delay: 00:02:00
# need to fix this. If we close the door during this time... it does not turn off the input booleans
#    - condition: state
#      entity_id: cover.chicken_door
#      state: 'open'
    - service: notify.telegram_group
      data:
        title: "\U0001F414 Last Call - Chicken Door \U0001F414"
        message: >
          {% if is_state('cover.chicken_door', 'closed') %}
            The chicken door was closed during last call.
          {% else %}
            The chicken door is still open ill close it now.
          {% endif %}
        data:
          inline_keyboard:
           - 'Open Door:/CHICKEN_OPEN_DOOR'
           - 'Close Door:/CHICKEN_CLOSE_DOOR'
    - service: homeassistant.turn_off
      data: 
        entity_id: >-
          {% if ( states.cover.chicken_door.state == 'closed') %}input_boolean.chicken_door_last_call, switch.4chpro_2, input_boolean.chicken_door_automations
          {% else %} light.null
          {% endif %}
    - condition: state
      entity_id: cover.chicken_door
      state: 'open'  
    - service: cover.close_cover
      data: 
        entity_id: >
          {% if ( states.cover.chicken_door.state == 'open') -%}
            cover.chicken_door
          {%- else -%}
            none
          {%- endif -%}
#    - service: cover.close_cover
#      entity_id: cover.chicken_door
    - wait_template: "{{ is_state('cover.chicken_door', 'closed') }}"
      timeout: 00:00:15
    - service: notify.telegram_group
      data:
        title: "\U0001F414 Last Call - Chicken Door \U0001F414"
        message: >
          {% if is_state('cover.chicken_door', 'closed') %}
            I closed the chicken door after last call.
          {% else %}
            I tried to close the chicken door after last call but it did not close!
          {% endif %}
        data:
          inline_keyboard:
           - 'Open Door:/CHICKEN_OPEN_DOOR'
           - 'Close Door:/CHICKEN_CLOSE_DOOR'
    - service: homeassistant.turn_off
      entity_id: input_boolean.chicken_door_last_call, switch.4chpro_2, input_boolean.chicken_door_automations
    - service: homeassistant.turn_on
      entity_id: automation.chicken_pen_door_lockout, automation.chicken_coop_door_lockout  
      
      
      
- alias: Chicken -  Chicken Door Timer Disabled
  initial_state: true
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.chicken_door_time.state }}'
  condition:
    - condition: state
      entity_id: input_boolean.chicken_door
      state: 'off'
    - condition: state
      entity_id: cover.chicken_door
      state: 'closed'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    - service: notify.ios_group
      data:
        title: 'Warning - Chicken Door'
        message: >
          "The chicken door did not open"
        data:
          push:
            category: 'chicken_door'

- alias: Chicken - Sunset Light on
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'
    - platform: time_pattern
      minutes: '/5'
      seconds: 00
  condition:
    - condition: state
      entity_id: cover.chicken_door
      state: 'open'
    - condition: sun
      after: sunset
      after_offset: '-00:28:00'
    - condition: state
      entity_id: switch.4chpro_2
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.4chpro_2
#     data:
#      brightness: 1

- alias: Chicken - Afterdark, door closed turn off light
  trigger:
   platform: state
   entity_id: cover.chicken_door
   from: 'open'
   to: 'closed'
   for:
     minutes: 2
  condition:
    - condition: state
      entity_id: switch.4chpro_2
      state: 'on'
  action:
   - service: homeassistant.turn_off
     entity_id: switch.4chpro_2

- alias: Chicken - IOS Handler
  trigger:
    platform: event
    event_type: ios.notification_action_fired
  condition:
   condition: template
   value_template: "{{(trigger.event.data.actionName.split('_')[0] == 'CHICKEN')}}"
  action:
   service: >-
     {% if (trigger.event.data.actionName.split('_')[1] == 'OPEN' ) and ( states.cover.chicken_door.state == 'closed')   %}
       cover.open_cover
     {% elif (trigger.event.data.actionName.split('_')[1] == 'CLOSE' ) and ( states.cover.chicken_door.state == 'open')  %}
       cover.close_cover
     {% else %}
     {% endif %}
   data:
    entity_id: cover.chicken_door

- alias: Chicken -  Boorder turn on light at sunrise
  trigger:
   platform: sun
   event: sunrise
   offset: '-00:20:00'
  action:
   service: homeassistant.turn_on
   entity_id: light.ge_daylight_b1510014_level_on_off
   
- alias: Chicken -  Brooder turn off light at sunset
  trigger:
   - platform: sun
     event: sunset
     offset: '+00:20:00'
  action:
   service: homeassistant.turn_off
   entity_id: light.ge_daylight_b1510014_level_on_off
      

- alias: Chicken - Brooder Thermostat
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.brooder_target_temp
    - platform: homeassistant
      event: start
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.brooder
        temperature: '{{states.sensor.brooder_target_temp.state | int }}'


- alias: Chicken - Pen Door Lockout
  initial_state: true
  trigger:
   platform: state
   entity_id: switch.sensornode2_relay1
   to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.sensornode2_relay1
      
- alias: Chicken - Coop Door Lockout
  initial_state: true
  trigger:
   platform: state
   entity_id: switch.sensornode2_relay2
   to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.sensornode2_relay2
