- alias: Climate - Send Message on colder outside than inside
#  initial_to: True
  trigger:
    - platform: state
      entity_id: sensor.dark_sky_temperature
  condition:
     - condition: state
       entity_id: climate.home
       state: 'cool'
     - condition: template
       value_template: "{{ states('sensor.5in1_temperature') < states('input_number.climate_set_temp') }}"
     - condition: state
       entity_id: cover.windows
       state: 'closed'
  action:
    - service: notify.mobile_app_ryan_iphone
      data:
        title: 'Colder outside than inside set temp.'
        message: >
          Outside temp is {{ states('sensor.5in1_temperature') }} and inside set temp is {{ states('sensor.input_number.climate_set_temp') }} Cool is off
    - service: climate.set_operation_mode
      data:
        entity_id: climate.home
        operation_mode: 'off'



- alias: Climate - Send Message on hotter outside than inside
#  initial_state:: True
  trigger:
    - platform: state
      entity_id: sensor.dark_sky_temperature
  condition:
     - condition: state
       entity_id: climate.home
       state: 'off'
     - condition: template
       value_template: "{{ states('sensor.5in1_temperature') > states('input_number.climate_set_temp') }}"
     - condition: state
       entity_id: cover.windows
       state: 'closed'
  action:
    - service: notify.mobile_app_ryan_iphone
      data:
        title: 'Hotter outside than inside set temp.'
        message: >
          Outside temp is {{ states('sensor.5in1_temperature') }} and inside set temp is {{ states('input_number.climate_set_temp') }} Cool is on
    - service: climate.set_operation_mode
      data:
        entity_id: climate.home
        operation_mode: 'cool'

- alias: Climate - Set backdrop slider
#  initial_state:: True
  trigger:
    platform: state
    entity_id: sensor.climate_set_temp
  condition:
    condition: template
    value_template: "{{ states.sensor.climate_set_temp.state != 'None' }}"
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.climate_set_temp
      value: "{{  states('sensor.climate_set_temp')  }}"

- alias: Climate - windows open turn off climate
#  initial_to: True
  trigger:
    - platform: state
      entity_id: cover.windows
      to: 'open'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.home
        operation_mode: 'off'