- alias: Dasher - turn off Hot Water
  trigger:
    - platform: event
      event_type: ac:63:be:ab:d5:5c
  action:
    - service: homeassistant.turn_off
      entity_id: switch.hot_water


- alias: Dasher Bed time
  trigger:
    - platform: event
      event_type: ac:63:be:91:20:72
  action:
    - service: homeassistant.turn_on
      entity_id: scene.goodnight

- alias: Dasher Leaving Home
  trigger:
    - platform: event
      event_type: 50:f5:da:7b:f3:bb
  action:
    - service: homeassistant.turn_on
      entity_id: scene.leaving_home

#- alias: Send Message when Dasher changes
#  trigger:
#    - platform: state
#      entity_id: binary_sensor.dasher
#  condition:
#   condition: state
#   entity_id: input_boolean.ha_start_delay
#   to: 'on'
#  action:
#   service: notify.ios_ryans_iphone_app
#   data_template:
#          message: >
#              Dasher is {{ states('binary_sensor.dasher') }}.
        