- alias: Door Chime - Door Open
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_entry_door, binary_sensor.wink_front_door_opened, binary_sensor.wink_back_door_opened, binary_sensor.basement_door, binary_sensor.front_door
      to: 'on'
  condition:
   condition: state
   entity_id: group.device_family
   state: 'home'
  action:
   service: wink.enable_chime
   entity_id: wink.dome
   data:
     tone: alert
     
- alias: Door Chime - Garage - Door Open
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_entry_door, cover.myq_first_bay, cover.myq_second_bay ,cover.myq_third_bay
      to: 'on'
  condition:
   condition: state
   entity_id: group.device_family
   state: 'home'
  action:
   - service: wink.enable_chime
     entity_id: wink.dome
     data:
       tone: alert
   - service: notify.hallway
     data:
       message: > 
        {{ trigger.to_state.name }} is {{ trigger.to_state.state }}


- alias: No one is home - Door Chime
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_entry_door, binary_sensor.wink_front_door_opened, binary_sensor.wink_back_door_opened, binary_sensor.basement_door, binary_sensor.front_door
      to: 'on'
  condition:
    - condition: state
      entity_id: group.device_family
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.house_guest
      state: 'off'
  action:
   service: wink.enable_chime
   entity_id: wink.dome
   data:
     tone: alert
 
