- alias: Garage Send Message when chelsea left but garage door is still open
  id: c0237af6-5122-4830-930c-14540144d635
  trigger:
   platform: state
   entity_id: person.chelsea
   to: 'not_home'
   for:
     minutes: 10
  condition:
   condition: or
   conditions:
   - condition: state
     entity_id: cover.myq_first_bay_2
     state: 'open'
  action:
   service: notify.telegram_ryan
   data:
      title: 'Chelsea Left'
      message: "First Bay was left open"
 #     data:
 #       push:
 #         category: 'door_close'
 
 
#this causes multiple lines, we should update this to show all door states.
- alias: Garage Send Message when everyone left and a door is open.
  id: 446f9d1f-c2bd-490e-9abd-c0b71b6af8ab
  trigger:
   platform: state
   entity_id: group.device_family
   to: 'not_home'
   for:
     minutes: 5
  condition:
   condition: state
   entity_id: group.garage
   state: 'open'
  action:
   service: notify.ios_group
   data:
          title: 'Garage Door Left Open'
          message: >
            {% if is_state('cover.myq_first_bay_2', 'open') -%}
              First Bay is open.
            {% endif -%}
            {% if is_state('cover.myq_second_bay_2', 'open') -%}
              Second Bay is open.
            {% endif -%}
            {%- if is_state('cover.myq_third_bay_2', 'open') -%}
              Third Bay is open
            {% endif -%}
          data:
           push:
            category: 'door_close'



- alias: Garage Send Message when no one is home but a garage door was open was opened
  id: d799e871-57fd-4b74-abc2-a495bdf022b3
  trigger:
    - platform: state
      entity_id: cover.myq_first_bay_2, cover.myq_second_bay_2, cover.myq_third_bay_2
      to: 'open'
      for:
        minutes: 1
  condition:
   condition: state
   entity_id: group.device_family
   state: 'not_home'
  action:
   service: notify.ios_group
   data:
      title: 'Something happened at home'
      message: >
        "No one is home and {{ trigger.to_state.name }} was opened"
      data:
        push:
          category: camera
        entity_id: camera.d239