- alias: Garage open turn garage light on for 10 minutes unless it is already on
  id: 2c920f27-ff6c-435d-97f8-8b44075e72db
  trigger:
#    - platform: state
#      entity_id: binary_sensor.garage_entry_door
#      from: 'off'
#      to 'on'
    - platform: state
      entity_id: cover.ratgdo_51357_door, cover.ratgdo_20157_door, cover.ratgdo_88676_door
      from: 'closed'
      to: 'opening'
  condition:
     - condition: state
       entity_id: sun.sun
       state: 'below_horizon'
     - condition: state
       entity_id: binary_sensor.still_dark
       state: 'on'
#     - condition: state
#       entity_id: light.garage_lights_front
#       state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: light.garage_lights_front, switch.ahr_085_2_relay2
    - service: timer.start
      entity_id: timer.back_flood, timer.garage_lights
      data:
        duration: '00:10:00'
    - delay: 00:01:00
    - condition: template
      value_template: >
        {% set new = trigger.entity_id %}
        {{ is_state(new, 'open') }}
    - wait_template: >
       {% set new = trigger.entity_id %}
       {{ is_state(new, 'closed') }}
#    - wait_template: "{{is_state('group.all_garage_doors', 'closed')}}"
      timeout: 00:10:00
    - service: homeassistant.turn_off
      entity_id: light.garage_lights_front
      
      
- alias: Garage Doors open turn garage light on for 10 minutes unless it is already on
  id: 22de2095-dd7a-4d3e-b99d-aafcb8e40102
  trigger:
    - platform: state
      entity_id: cover.ratgdo_51357_door, cover.ratgdo_20157_door, cover.ratgdo_88676_door
      from: 'closed'
      to: 'opening'
  action:
    - service: homeassistant.turn_on
      entity_id: light.garage_lights_front
    - service: timer.start
      entity_id: timer.garage_lights
      data:
        duration: '00:10:00'
    - delay: 00:01:00
    - condition: template
      value_template: >
        {% set new = trigger.entity_id %}
        {{ is_state(new, 'open') }}
    - wait_template: >
       {% set new = trigger.entity_id %}
       {{ is_state(new, 'closed') }}
      timeout: 00:10:00
    - service: homeassistant.turn_off
      entity_id: light.garage_lights_front
