- alias: HA Starts - Send Message
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: 00:00:15
    - service: notify.telegram_ryan
      data:
        title: "Ha Start"
        message: >
          {% for entity in states.group.processes.attributes.entity_id if is_state(entity, 'on')-%}
          {% set closed_loop = loop %}
            {%- if closed_loop.length ==6 and closed_loop.first %}All the processes are running.{% endif -%}
            {%- if closed_loop.length <6 %}
            {%- if closed_loop.first %}Running:  {% elif closed_loop.last %} and {% else %} {% endif -%}
              {{state_attr(entity, 'friendly_name')}}
            {%- endif %}
          {%- endfor %}
       
          {% for entity in states.group.processes.attributes.entity_id if is_state(entity, 'off')-%}
          {% set open_loop = loop %}
            {%- if open_loop.length ==6 and open_loop.first %}All the processes are stopped.{% endif -%}
            {%- if open_loop.length <6 %}
            {%- if open_loop.first %}Stopped:  {% elif open_loop.last %} and {% else %} {% endif -%}
              {{state_attr(entity, 'friendly_name')}}
            {%- endif %}
          {%- endfor %}
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff_basement/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff4chpro/POWER1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff4chpro/POWER2"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff4chpro/POWER3"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff4chpro/POWER4"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sensornode2/POWER1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sensornode2/POWER2"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sensornode2/POWER3"
        payload: ""

- alias: HA Stop - Send Message stop timers
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    - service: notify.telegram_ryan
      data:
       title: 'Home Assistant Stop'
      data:
           message: >
             Ha is Shutting Down
    - service: timer.finish
      entity_id: all



- alias: HA Start - Set front timers if lights on
  trigger:
    - platform: homeassistant
      event: start
  condition:
     - condition: state
       entity_id: light.wink_front_porch
       state: 'on'
  action:
    - service: timer.start
      entity_id: timer.front_porch
      data:
        duration: '00:10:00'
        
        
- alias: HA Start - Set flood timers if lights on
  trigger:
    - platform: homeassistant
      event: start
  condition:
     - condition: state
       entity_id: switch.wink_back_flood
       state: 'on'
  action:
    - service: timer.start
      entity_id: timer.back_flood
      data:
        duration: '00:10:00'

        
        
             