- alias: Hotwater - Turn off hot water at 8 if no one is home
  id: fa6de1fa-a8c3-4250-8070-e3c0108250fd
  trigger:
   platform: time
   at: '08:00:00'
  condition:
     - condition: state
       entity_id: group.device_family
       state: 'not_home'
     - condition: state
       entity_id: input_boolean.house_guest
       state: 'off'
  action:
   service: homeassistant.turn_off
   entity_id: switch.wink_zwaveoutlet
   
- alias: Turn on hot water at 5
  id: 1fd3a429-76be-4070-a118-f1d81d3d5e56
  trigger:
   platform: time
   at: '17:00:00'
  action:
   service: homeassistant.turn_on
   entity_id: switch.wink_zwaveoutlet
   
- alias: Hotwater -  Came home early
  id: fd008b40-5380-457d-9e62-d6a54ce95015
  trigger:
    platform: state
    entity_id: person.chelsea, person.ryan
    from: 'not_home'
    to: 'home'
    for:
      minutes: 10
  condition:
     - condition: state
       entity_id: switch.wink_zwaveoutlet
       state: 'off'
     # - condition: template
       # value_template: "{{trigger.from_state.attributes.source_type == 'gps'}}"
  action:
    -  service: notify.telegram_ryan
       data:
         title: "You are Home and ..."
         message: >
           The Hotwater is off.
#         data:
#           push:
#             category: 'hot_water'
             
- alias: Hotwater - IOS
  id: 5ac7ee53-0e85-4c75-a8d1-d350d8ab234a
  trigger:
    platform: event
    event_type: ios.notification_action_fired
  condition:
   condition: template
   value_template: "{{(trigger.event.data.actionName == 'TURN_ON_HOT_WATER')}}"
  action:
   service: homeassistant.turn_on
   entity_id: switch.wink_zwaveoutlet
