#- alias: Notify iOS moving
#  trigger:
#    platform: state
#    entity_id: device_tracker.ryans_iphone_app2
#  action:
#    service: notify.ios_ryans_iphone_app
#    data:
#      message: >
#        {{trigger.from_state}}
#        {{trigger.to_state}}
#        {%- for attr in states.device_tracker.ryans_iphone_app2.attributes -%}
#        {%- if  attr not in ["attribution" , "friendly_name", "source_type"]%}
#        {{attr.replace("_", " ")| capitalize}}: {{states.device_tracker.ryans_iphone_app2.attributes[attr] }} 
#        {%- endif %}
#        {%- endfor %}
#        {{states.device_tracker.ryans_iphone_app2.state}}
#        {{trigger.from_state}}
#        {{trigger.to_state}}



- alias: Notify iOS moving
  id: 6877d84a-da73-48c7-97fe-6f0b1d6a553c
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.ryans_iphone_app2
  action:
    service: notify.ios_ryans_iphone_app
    data:
      message: >
         "your location"
#        {{trigger.from_state}}
#        {{trigger.to_state.attributes.latitude}}
      data:
        push:
          category: map
        action_data:
          latitude: "{{trigger.to_state.attributes.latitude}}"
          longitude: "{{trigger.to_state.attributes.longitude}}"


#{{ states.device_tracker.ryans_iphone_app2 }} 
#{{ states.device_tracker.ryans_iphone_app2.attributes.latitude}}


- alias: Notify iOS moving test
  id: 651594e2-4d0c-47d6-a7c1-e47a545e2a30
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.ryans_iphone_app2
  action:
    service: notify.ios_ryans_iphone_app
    data:
      message: >
        {{trigger.from_state}}
        {{trigger.to_state}}