- alias: Ios All In one  True - IOS
  id: cce93be9-33ee-4af6-949e-74030340e827
  trigger:
    platform: event
    event_type: ios.notification_action_fired
  condition:
   condition: template
   value_template: "{{(trigger.event.data.actionName.split('_')[0] == 'ALLINONE')}}"
  action:
    - service: >-
        {% set domain = (trigger.event.data['action_data']['entity_id'].split('.')[0]) %}
        {% set function = (trigger.event.data.actionName.split('_')[1]) %}
        {% set entity_id = (trigger.event.data['action_data']['entity_id']) %}
        {% if (function == 'TRUE') -%}
          {% if (domain == 'cover') -%}
            cover.open_cover
          {% elif (domain in ['light', 'switch', 'script', 'automation', 'input_boolean', 'group']) -%}
            homeassistant.turn_on
          {% elif (domain == 'lock') -%}
            lock.lock
          {% else -%}
          Invalid Domain:{{domain}} Function: {{function}} or entity:{{entity_id}}
          {% endif -%}
        {% elif (function == 'FALSE') -%}
          {% if (domain == 'cover') -%}
            cover.close_cover
          {% elif (domain in ['light', 'switch', 'script', 'automation', 'input_boolean', 'group']) -%}
            homeassistant.turn_off
          {% elif (domain == 'lock') -%}
            lock.unlock
          {% else -%}
          Invalid Domain:{{domain}} Function: {{function}} or entity:{{entity_id}}
          {% endif -%}
        {% else -%}
        Invalid Domain:{{domain}} Function: {{function}} or entity:{{entity_id}}
        {% endif -%}
      data:
       entity_id: "{{trigger.event.data['action_data']['entity_id']}}"

    - service: persistent_notification.create
      data:
        title: 5
        message: >
         {{trigger.event.data['action_data']['entity_id']}}

 
- alias: Ios Notify iOS app test
  id: c442aa21-02ee-4016-96ea-741a60fe4434
  trigger:
    platform: event
    event_type: ios.notification_action_fired2
  action:
        service: notify.ios_ryans_iphone_app
        data:
          message: "What should I do with the chicken door?"
          data:
            push:
              category: 'camera'
            entity_id: camera.camd239
            action_data:
              entity_id: light.wink_office
          
