- alias: iOS message test
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.ryans_iphone_app2
  action:
    -  service: notify.ios_ryans_iphone_app
       data:
         message: "camera and actions"
         data:
           push:
             category: 'camera'
           entity_id: camera.camd239