- alias: Back Door open and light is already on via door open keep light on for another 10.
  id: bf33ec5c-d404-4ac6-b69a-fba25893365a
  trigger:
    - platform: state
      entity_id: binary_sensor.wink_back_door_opened, binary_sensor.garage_entry_door
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.wink_back_door_opened, binary_sensor.garage_entry_door
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: cover.ratgdo_51357_door, cover.ratgdo_20157_door, cover.ratgdo_88676_door
      from: 'closed'
      to: 'open'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: binary_sensor.still_dark
      state: 'on'
    - condition: state
      entity_id: timer.back_flood
      state: 'active'
    - condition: state
      entity_id: input_boolean.fox_hunt
      state: 'off'
  action:
    - service: timer.start
      entity_id: timer.back_flood
      data:
        duration: '00:10:00'




- alias: Back Door open turn flood light on for 10 minutes unless it is already on.
  id: 35ca564d-03d3-4fde-92ae-edd69e90b3b2
  trigger:
    - platform: state
      entity_id: binary_sensor.wink_back_door_opened, binary_sensor.garage_entry_door
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.wink_back_door_opened, binary_sensor.garage_entry_door
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: switch.wink_back_flood
      state: 'off'
    - condition: state
      entity_id: binary_sensor.still_dark
      state: 'on'
    - condition: state
      entity_id: input_boolean.fox_hunt
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.wink_back_flood
    - service: timer.start
      entity_id: timer.back_flood
      data:
        duration: '00:10:00'
      
   
   
- alias: Garage open turn flood light on for 10 minutes unless it is already on
  id: 77e3f77e-ab8c-4bdb-9ee7-16fe685686cd
  trigger:
    - platform: state
      entity_id: cover.ratgdo_51357_door, cover.ratgdo_20157_door, cover.ratgdo_88676_door
      from: 'closed'
      to: 'open'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: switch.wink_back_flood
      state: 'off'
    - condition: state
      entity_id: binary_sensor.still_dark
      state: 'on'
    - condition: state
      entity_id: input_boolean.fox_hunt
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.wink_back_flood
    - service: timer.start
      entity_id: timer.back_flood
      data:
        duration: '00:10:00'
