- alias: Front Door open turn porch light on unless it is already on
  id: 3ad9b428-1bdf-4764-8fff-ed77fbd2f8ae
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: 'off'
      to: 'on'
  condition:
     - condition: state
       entity_id: sun.sun
       state: 'below_horizon'
     - condition: state
       entity_id: switch.wink_front_porch_switch
       state: 'off'
     - condition: state
       entity_id: binary_sensor.still_dark
       state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.wink_front_porch_switch
    - service: timer.start
      entity_id: timer.front_porch
      data:
        duration: '00:10:00'
      
      
- alias: 13. Front Door open and light is already on via door keep light on for another 10.
  id: c1af46ed-182d-4878-b990-d6cdec2be3c8
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: timer.front_porch
      state: 'active'
    - condition: state
      entity_id: binary_sensor.still_dark
      state: 'on'
  action:
#    - service: homeassistant.turn_off
#      entity_id: script.timer_off
#    - service: homeassistant.turn_on
#      entity_id: script.timer_off
    - service: timer.start
      entity_id: timer.front_porch
      data:
        duration: '00:10:00'
       
       
       
- alias: Garage open turn front porch light on for 10 minutes unless it is already on
  id: c8b85d93-ec78-43f2-a91a-6562f2e9fdc7
  trigger:
    - platform: state
      entity_id: cover.ratthirdbay_door, cover.ratsecondbay_door, cover.rat_firstbay_11e249_door
      from: 'closed'
      to: 'open'
  condition:
     - condition: state
       entity_id: sun.sun
       state: 'below_horizon'
     - condition: state
       entity_id: switch.wink_front_porch_switch
       state: 'off'
     - condition: state
       entity_id: binary_sensor.still_dark
       state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.wink_front_porch_switch
    - service: timer.start
      entity_id: timer.front_porch
      data:
        duration: '00:10:00'
      