- alias: 'Ryan Away'
  id: 595826cf-71de-4d82-a4a0-5ca13c94a565
  condition:
    condition: state
    entity_id: input_boolean.device_ryan
    state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.ryans_iphone_wifi
      to: 'not_home' 
      for:
        minutes: 10
    - platform: state
      entity_id: device_tracker.ryans_iphone_app2
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.ryans_iphone_app2
      from: 'home'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.device_ryan
      
      
- alias: 'Ryan Home'
  id: ffe454a3-871a-4343-810b-1547b1b98961
  condition:
    condition: state
    entity_id: input_boolean.device_ryan
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.ryans_iphone_wifi
      to: 'home'
    - platform: state
      entity_id: device_tracker.ryans_iphone_app2
      to: 'home'   
  action:
     service: homeassistant.turn_on
     entity_id: input_boolean.device_ryan

 

- alias: 'Chelsea Away'
  id: d9404d8b-a216-4077-9e41-ecb191338a23
  condition:
    condition: state
    entity_id: input_boolean.device_chelsea
    state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.chelseas_iphone_wifi
      to: 'not_home' 
      for:
        minutes: 10
    - platform: state
      entity_id: device_tracker.chelseasiphone
      to: 'not_home'   
    - platform: state
      entity_id: device_tracker.chelseas_iphone_app
      to: 'not_home'   
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.device_chelsea
      
      
- alias: 'Chelsea Home'
  id: 7ed632f2-dbbe-4c0b-b19a-5e3ada25e4cf
  condition:
    condition: state
    entity_id: input_boolean.device_chelsea
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.chelseas_iphone_wifi
      to: 'home'
    - platform: state
      entity_id: device_tracker.chelseasiphone
      to: 'home'
    - platform: state
      entity_id: device_tracker.chelseas_iphone_app
      to: 'home' 
  action:
     service: homeassistant.turn_on
     entity_id: input_boolean.device_chelsea