- alias: Send Message when no one is home but a door was opened v2
  id: 902b8d70-d603-4c09-9226-4824f9376f5f
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_entry_door, binary_sensor.wink_front_door_opened, binary_sensor.wink_back_door_opened, binary_sensor.basement_door, binary_sensor.front_door
      to: 'on'
  condition:
   condition: state
   entity_id: group.device_family
   state: 'not_home'
  action:
    - wait_template: >
       {% set new = trigger.entity_id %}
       {{ is_state(new, 'off') }}
      timeout: 00:00:05
    - service: notify.everyone_group
      data:
        title: Something happened at home
        message: >
          {% set new = trigger.entity_id %}
          {% if is_state(new, 'off') %}
            No one is home and {{ trigger.to_state.name }} was opened and closed.
          {% else %}
            No one is home and {{ trigger.to_state.name }} was opened.
          {% endif %}
    - condition: template
      value_template: >
        {% set new = trigger.entity_id %}
        {{ is_state(new, 'on') }}
    - wait_template: >
       {% set new = trigger.entity_id %}
       {{ is_state(new, 'off') }}
    - service: notify.everyone_group
      data:
       title: Something happened at home
       message: >
         No one is home and {{ trigger.to_state.name }} was closed


- alias: Send Message on state changes
  id: 775a4c37-f772-4d76-920e-c802e27cb232
#  initial_to: False
  trigger:
    - platform: state
      entity_id: switch.wink_zwaveoutlet, binary_sensor.climate_aux_heat, binary_sensor.device_vehicle_jeep, binary_sensor.device_vehicle_mazda
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: switch.wink_zwaveoutlet, binary_sensor.climate_aux_heat, binary_sensor.device_vehicle_jeep, binary_sensor.device_vehicle_mazda
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.wink_hub
      to: 'off'
      for:
        minutes: 1
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
    - platform: numeric_state
      entity_id: sensor.disk_use_percent
      above: 90
  action:
   service: notify.telegram_ryan
   data:
      title: 'A state changed'
      message: >
        {{ trigger.to_state.name }} is {{ trigger.to_state.state }}
       
