- alias: Smoke Detected
  trigger:
    - platform: state
      entity_id: sensor.smoke_status
      to: 'smoke'
    - platform: state
      entity_id: sensor.smoke_status
      to: 'co'
    - platform: state
      entity_id: sensor.smoke_status
      to: 'test'
    - platform: state
      entity_id: sensor.smoke_status
      to: 'unknown'
      from: 'OK'
  action:
    - service: notify.twilio_call
      data:
        target:
          - +12406728691
          - +14105996687
        message: >
          {% set door = trigger.entity_id.split('.')[1] | capitalize %}
          {{ door }} Triggered at Home, Repeat, {{ door }} Triggered at Home, Repeat, {{ door }} Triggered at Home
    - service: notify.everyone_group
      data:
        title: 'CO or Smoke Detected'
        message: >
          {% set door = trigger.entity_id.split('.')[1] | capitalize %}
          {{ door }} Triggered at Home
    - service: homeassistant.turn_on
      entity_id: group.indoor_lights
    - service: climate.set_operation_mode
      data:
        entity_id: climate.wink_home, climate.home
        operation_mode: off
    - service: climate.set_fan_mode
      data:
        entity_id: climate.wink_home, climate.home
        fan_mode: 'off'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.wink_home, climate.home
        operation_mode: off
    - service: climate.set_fan_mode
      data:
        entity_id: climate.wink_home, climate.home
        fan_mode: 'off'