- alias: 'Speed test'
  trigger:
    platform: time_pattern
    # You can also match on interval. This will match every 5 minutes
    minutes: "1"
  condition:
    condition: state
    entity_id: device_tracker.livingroomtv
    state: 'not_home'
  action:
     service: speedtestdotnet.speedtest