- alias: Test - Send Message when input boolean change
  id: 9ffb4966-5cc2-4eb3-b559-fe9a6597e51c
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.test
      from: 'off'
      to: 'on'
  action:
    -  service: persistent_notification.create
       data:
         title: "Before"
         message: >
          {{states(trigger.entity_id)}}
          {{is_state(trigger.entity_id,'off')}}
    - wait_template: "{{is_state('trigger.entity_id','off')}}"
      timeout: 00:00:30
    -  service: persistent_notification.create
       data:
         title: "After"
         message: >
          {{trigger.entity_id}}
          {{is_state(trigger.entity_id,'off')}}

        
#- alias: test wait state
#  initial_state: 'off'
#  trigger:
#    platform: state
#    entity_id: device_tracker.ryans_iphone_app2
#  action:
#    - service: notify.ios_ryans_iphone_app
#      data:
#        message: "before wait states"
#    - wait_template: "{{states.input_boolean.test.state == on}}"
#      timeout: 00:01:00
#    - service: notify.ios_ryans_iphone_app
#      data:
#        message: "after wait states"

#- alias: test wait is_state
#  initial_state: 'off'
#  trigger:
#    platform: state
#    entity_id: device_tracker.ryans_iphone_app2
#  action:
#    - service: notify.ios_ryans_iphone_app
#      data:
#        message: "before wait is state"
#    - wait_template: "{{is_state('input_boolean.test', 'on')}}"
#      timeout: 00:01:00
#    - service: notify.ios_ryans_iphone_app
#      data:
#        message: "after wait is state"

- alias: test wait state
  id: 2884a864-4c88-4acd-bce7-4fea1c8e148c
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.ryans_iphone_app2
  action:
    - service: notify.ios_ryans_iphone_app
      data:
        message: "before wait states"
    - wait_template: "{{states.input_boolean.test.state == on}}"
      timeout: 00:01:00
    - service: notify.ios_ryans_iphone_app
      data:
        message: "after wait states"

- alias: test badge2
  id: f2f3a3a9-14a7-4354-9c3f-fc863897d18e
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.ryans_iphone_app2
  action:
    - service: notify.ios_ryans_iphone_app2
      data:
        message: "after wait is state"
        data:
          push:
            badge: 1
        
- alias: test badge
  id: 20dc3acc-8430-48a3-8ff8-0b0b1a4729f2
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.ryans_iphone_app2
  action:
    - service: notify.ios_ryans_iphone_app2
      data:
        message: "before wait is state"
        data:
          push:
            badge: '{{states.input_number.alarm_hour.state|int}}'
            
            
- alias: discord_test1
  id: 6b0f20db-5698-450d-90d1-af46b8b2a695
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.ryans_iphone_app2
  action:
    - service: homeassistant.turn_off
      data: 
        entity_id: >
          {%- if ( states.cover.chicken_door.state == 'closed') -%}
            input_boolean.chicken_door_last_call
          {%- else -%}
            none
          {%- endif -%}
            
- alias: discord_test2
  id: 8ab85e97-02ae-4401-b651-fe6eb6ca29c9
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.ryans_iphone_app2
  action:
    - service: homeassistant.turn_off
      data: 
        entity_id: >
          {%- if ( states.cover.chicken_door.state == 'closed') -%}
            input_boolean.chicken_door_last_call, switch.esp4, input_boolean.chicken_door_automations
          {%- else -%}
            none
          {%- endif -%}

- alias: discord_test3
  id: 3557c328-30d3-417a-b96d-04d303fef36b
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.ryans_iphone_app2
  action:
    - service: homeassistant.turn_off
      data: 
        entity_id: >- 
          {% if ( states.cover.chicken_door.state == 'closed') -%}input_boolean.chicken_door_last_call, switch.esp4, input_boolean.chicken_door_automations
          {%- else -%}none
          {%- endif -%}
          
- alias: discord_test4
  id: b3d21950-5838-408f-8502-a27587e289a4
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.ryans_iphone_app2
  action:
    - service: homeassistant.turn_off
      data: 
        entity_id: >- 
          {% if ( states.cover.chicken_door.state == 'closed') %}input_boolean.chicken_door_last_call
          {% else %}none
          {% endif %}