- alias: 'TV on dim the light'
  id: 9d1b965a-47f8-48fe-a24e-abb50a4b96f8
  trigger:
    - platform: state
      entity_id: device_tracker.livingroomtv
      to: 'home'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.tv_time_delay
      state: 'off'
  action:
     service: homeassistant.turn_on
     entity_id: scene.tv_time
     
     
- alias: 'TV off light the light'
  id: 9ef474a0-9fc3-465b-b059-90491945c822
  trigger:
    - platform: state
      entity_id: device_tracker.livingroomtv
      to: 'not_home'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: light.osram_lightify_a19_tunable_white_00094db0_3
      state: 'on'
  action:
   service: homeassistant.turn_on
   entity_id: scene.tv_time_over
   
# - alias: 'TV LED Random'
  # trigger: 
# #    - platform: time
# #      seconds: '/10'
    # - platform: time_pattern
      # minutes: 0
      # seconds: 0
  # condition: 
    # condition: state
    # entity_id: light.wink_led_strip_tv
    # state: 'on'
  # action:
    # - service: light.turn_on
      # data:
        # entity_id: light.wink_led_strip_tv
        # brightness_pct: 50
        # color_name: >
          # {{['aqua','seagreen','mediumslateblue','teal','blue','darkgreen','deepskyblue','green','indigo','magenta','midnightblue','orangered','hotpink','purple','red','violet','yellow']|random}}
# #        rgb_color: ['{{ (range(0, 255, 25)|random) }}', '{{ (range(0, 255, 25)|random) }}', '{{ (range(0, 255, 25)|random) }}']

- alias: 'TV reset tc_time_delay'
  id: 57d0e706-ddb5-486f-bc1f-c8738e96aa30
  trigger:
    - platform: state
      entity_id: input_boolean.tv_time_delay
      to: 'on'
      for:
        minutes: 60
  action:
     service: homeassistant.turn_on
     entity_id: input_boolean.tv_time_delay