- alias: Send Message when UPS on Batt
  trigger:
    - platform: state
      entity_id: sensor.syno_status_data
  action:
   service: notify.ios_ryans_iphone_app
   data_template:
          message: >
            {% if is_state('sensor.syno_status_data', 'OL') %}
              UPS is On
            {% else %}
              UPS is {{ states('sensor.syno_status_data') }}.
            {% endif %}
        

