
#Vacation Mode on
- alias: Turn on vacation mode
  trigger:
   platform: state
   entity_id: input_boolean.vacation_mode
   from: 'off'
   to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.wink_zwaveoutlet, automation.Turn_on_hot_water_at_5, automation.1_turn_on_light_when_sun_sets_and_noone_is_home

#Vacation Mode off
- alias: Turned off Vacation Mode
  trigger:
   platform: state
   entity_id: input_boolean.vacation_mode
   to: 'off'
   from: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.wink_zwaveoutlet, automation.Turn_on_hot_water_at_5, automation.1_turn_on_light_when_sun_sets_and_noone_is_home






# Vacation mode for Living Room light
- alias: 'Vacation Mode for Living Room ON'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:38:00"
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.wink_hallway

# Vacation mode for Living Room light
- alias: 'Vacation Mode for Living Room OFF'
  trigger:
    platform: sun
    event: sunset
    offset: "+01:00:00"
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.wink_hallway


# Vacation mode for Bed Room light
- alias: 'Vacation Mode for Bed Room ON'
  trigger:
    platform: sun
    event: sunset
    offset: "+01:40:00"
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.wink_bed_room
# Vacation mode for Bed Room light
- alias: 'Vacation Mode for Bed Room OFF'
  trigger:
    platform: sun
    event: sunset
    offset: "+03:25:00"
  condition:
    condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.wink_bed_room
