language: python
python:
  - "3.7"
before_install:
  - echo -e "hello" > /tmp/adbkey
  - echo -e "hello" > /tmp/adbkey.pub
  - mv travis_secrets.yaml secrets.yaml
  - rm /config/packages/custom_components.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
  
