language: python
python:
  - "3.6"
before_install:
  - echo -e "hello" > /tmp/adbkey
  - echo -e "hello" > /tmp/adbkey.pub
  - mv travis_secrets.yaml secrets.yaml
  - pip install deepstack-python
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
  
