language: python
python:
  - "3.5"
before_install:
  - echo -e "hello" > /tmp/adbkey
  - echo -e "hello" > /tmp/adbkey.pub
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
  