language: python
python:
  - "3.5"
before_install:
  - mkdir /root
  - mkdir /root/.android
  - echo -e "hello" > /root/.android/adbkey
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
  