- id: '1540006472019'
  alias: New Automation
  trigger: []
  condition: []
  action: []
- id: '1584913993330'
  alias: Bathroom Vent
  description: ''
  trigger:
  - above: '95'
    entity_id: sensor.bathroom_humid
    for: 00:03:00
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.bathroom_fan
    service: switch.turn_on
  mode: single
- id: '1584914187902'
  alias: Bathroom Vent Off
  description: ''
  trigger:
  - below: '89'
    entity_id: sensor.bathroom_humid
    for: 00:01:00
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.bathroom_fan
    service: switch.turn_off
- id: '1611147472037'
  alias: Snooze Alarm
  description: ''
  trigger:
  - platform: event
    event_type: shortcut_event
    event_data:
      actionname: snooze-alarm
  condition: []
  action:
  - service: light.turn_on
    data:
      effect: rainbow
    target:
      entity_id: light.bed_wled
  - service: light.turn_on
    data: {}
    entity_id: light.bed_wled
  - service: number.set_value
    target:
      entity_id: number.bed_wled_intensity
    data:
      value: '120'
  - service: number.set_value
    target:
      entity_id: number.bed_wled_speed
    data:
      value: '5'
  # - service: light.turn_on
    # data:
      # effect: sunrise
    # target:
      # entity_id: light.bed_wled
      # intensity: 120
      # speed: 5
    # entity_id: light.bed_wled
  mode: single
- id: '1614888725831'
  alias: record cumulative rain to midnight
  description: ''
  trigger:
  - platform: time_pattern
    hours: '00'
    minutes: '00'
    seconds: '01'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: ha/cum_rain_prior
      retain: true
      payload_template: '{{ states(''sensor.pws_5in1_total_rain'') }}'
  mode: single
- id: '1639314659508'
  alias: outside christmas tree on
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '0'
  condition: []
  action:
  - service: homeassistant.turn_on
    target:
      entity_id: switch.esp11
  mode: single
- id: '1639314713123'
  alias: outside christmas tree off
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '0'
  condition: []
  action:
  - service: homeassistant.turn_off
    target:
      entity_id: switch.esp11
  mode: single
