- id: '1540006472019'
  alias: New Automation
  trigger: []
  condition: []
  action: []
- id: '1584913993330'
  alias: Bathroom Vent
  description: ''
  trigger:
  - above: '95'
    entity_id: sensor.bathroom_humid
    for: 00:03:00
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.bathroom_fan
    service: switch.turn_on
  mode: single
- id: '1584914187902'
  alias: Bathroom Vent Off
  description: ''
  trigger:
  - below: '89'
    entity_id: sensor.bathroom_humid
    for: 00:01:00
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.bathroom_fan
    service: switch.turn_off
- id: '1611147472037'
  alias: Snooze Alarm
  description: ''
  trigger:
  - platform: event
    event_type: shortcut_event
    event_data:
      actionname: snooze-alarm
  condition: []
  action:
  - service: wled.effect
    data:
      effect: Rainbow
    entity_id: light.bed_wled
  - service: light.turn_on
    data: {}
    entity_id: light.bed_wled
  - service: wled.effect
    data:
      effect: sunrise
      intensity: 120
      speed: 5
    entity_id: light.bed_wled
  mode: single
- id: '1614888725831'
  alias: record cumulative rain to midnight
  description: ''
  trigger:
  - platform: time_pattern
    hours: '00'
    minutes: '00'
    seconds: '01'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: ha/cum_rain_prior
      retain: true
      payload_template: '{{ states(''sensor.pws_5in1_total_rain'') }}'
  mode: single
