- id: '1540006472019'
  alias: New Automation
  trigger: []
  condition: []
  action: []
- id: '1584913993330'
  alias: Bathroom Vent
  description: ''
  trigger:
  - above: '95'
    entity_id: sensor.bathroom_humid
    for: 00:03:00
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.bathroom_fan
    service: switch.turn_on
  mode: single
- id: '1584914187902'
  alias: Bathroom Vent Off
  description: ''
  trigger:
  - below: '89'
    entity_id: sensor.bathroom_humid
    for: 00:01:00
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.bathroom_fan
    service: switch.turn_off
- id: '1611147472037'
  alias: Snooze Alarm
  description: ''
  trigger:
  - platform: event
    event_type: shortcut_event
    event_data:
      actionname: snooze-alarm
  condition: []
  action:
  - service: homeassistant.turn_on
    data:
      brightness_pct: 100
    entity_id: light.bed_wled
  - service: wled.effect
    data:
      effect: sunrise
      intensity: 120
      speed: 5
    entity_id: light.bed_wled
  mode: single
