- id: '1540006472019'
  alias: New Automation
  trigger: []
  condition: []
  action: []
- id: '1584913993330'
  alias: Bathroom Vent
  description: ''
  trigger:
  - above: '95'
    entity_id: sensor.bathroom_humid
    for:
      hours: 0
      minutes: 2
      seconds: 0
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.bathroom_fan
    service: switch.turn_on
  mode: single
- id: '1584914187902'
  alias: Bathroom Vent Off
  description: ''
  trigger:
  - below: '89'
    entity_id: sensor.bathroom_humid
    for: 00:01:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.bathroom_fan
    state: 'on'
  action:
  - data: {}
    entity_id: switch.bathroom_fan
    service: switch.turn_off
- id: '1611147472037'
  alias: Snooze Alarm
  description: ''
  trigger:
  - platform: event
    event_type: shortcut_event
    event_data:
      actionname: snooze-alarm
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.bed_wled
    data:
      effect: solid
      rgb_color:
      - 0
      - 0
      - 0
  - service: light.turn_on
    data:
      effect: Sunrise
    target:
      entity_id: light.bed_wled
  - service: number.set_value
    target:
      entity_id: number.bed_wled_intensity
    data:
      value: '120'
  - service: number.set_value
    target:
      entity_id: number.bed_wled_speed
    data:
      value: '5'
  mode: single
- id: '1614888725831'
  alias: record cumulative rain to midnight
  description: ''
  trigger:
  - platform: time_pattern
    hours: '00'
    minutes: '00'
    seconds: '01'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: ha/cum_rain_prior
      retain: true
      payload_template: '{{ states(''sensor.pws_5in1_total_rain'') }}'
  mode: single
- id: '1639314659508'
  alias: outside christmas tree on
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '0'
  condition: []
  action:
  - service: homeassistant.turn_on
    target:
      entity_id: switch.esp11
  mode: single
- id: '1639314713123'
  alias: outside christmas tree off
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: '0'
  condition: []
  action:
  - service: homeassistant.turn_off
    target:
      entity_id: switch.esp11
  mode: single
- id: '1641653770665'
  alias: alert-ack-home
  description: ''
  trigger:
  - platform: state
    entity_id: person.ryan
    from: not_home
    to: home
  condition: []
  action:
  - service: alert.turn_on
    data:
      entity_id: '{{ states.alert|selectattr(''state'',''eq'',''off'')|map(attribute=''entity_id'')|join('','')
        }}

        '
  - service: automation.turn_off
    target:
      entity_id:
      - automation.alert_ack_home
  mode: single
- id: '1641654143724'
  alias: alert-ack-morn
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.fry_battery_state
    from: Charging
    to: Not Charging
  condition:
  - condition: time
    after: 05:00:00
    before: '11:00:00'
  action:
  - service: alert.turn_on
    data:
      entity_id: '{{ states.alert|selectattr(''state'',''eq'',''off'')|map(attribute=''entity_id'')|join('','')
        }}

        '
  - service: automation.turn_off
    target:
      entity_id: automation.alert_ack_morn
  mode: single
- id: '1643123848197'
  alias: Node Red is dead
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.node_red_status
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.node_red_dead
  mode: single
- id: '1643221820085'
  alias: Tag chicken_feed is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 0921efce-ba6f-424a-a388-8980017719fc
  condition: []
  action:
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.chicken_last_feed
    data:
      timestamp: '{{ now().timestamp() }}'
  mode: single
- id: '1643221841875'
  alias: Tag chicken_eggs is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: f0cd9b85-9025-47f9-b951-b0710160b686
  condition: []
  action:
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.chicken_last_eggs
    data:
      timestamp: '{{ now().timestamp() }}'
  mode: single
- id: '1643221855990'
  alias: Tag chicken_water is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 488a6b96-4fe3-4521-a63e-d40b9b552e33
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      timestamp: '{{ now().timestamp() }}'
    target:
      entity_id: input_datetime.chicken_last_water
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.chickens_need_watering
  mode: single
- id: '1643722988108'
  alias: Turn off upstairs heat after 2 hours
  description: ''
  trigger:
  - platform: template
    value_template: '{{ is_state(''climate.bed_room'', ''heat'') or is_state(''climate.bed_room'',
      ''unavailable'') }}'
    for:
      hours: 2
  - platform: template
    value_template: '{{ is_state(''climate.craft_room'', ''heat'') or is_state(''climate.craft_room'',
      ''unavailable'') }}'
    for:
      hours: 2
  condition: []
  action:
  - service: climate.turn_off
    target:
      entity_id:
      - climate.bed_room
      - climate.craft_room
  mode: parallel
  max: 10
- id: '1652207706173'
  alias: Reset RTL
  description: ''
  trigger:
  - platform: state
    entity_id: alert.weather_station
    to: 'on'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: hassio.addon_restart
    data:
      addon: 9b13b3f4_rtl433
  mode: single
- id: '1657802534737'
  alias: Climate - Craft Room Cool - On
  description: ''
  trigger:
  - platform: template
    value_template: '{{states.climate.craft_room.attributes.current_temperature >
      states.climate.craft_room.attributes.temperature}}'
    for:
      minutes: 5
  condition:
  - condition: device
    device_id: 1da3570264a941bbf2a20e7f133f58af
    domain: climate
    entity_id: climate.craft_room
    type: is_hvac_mode
    hvac_mode: 'off'
  action:
  - device_id: 1da3570264a941bbf2a20e7f133f58af
    domain: climate
    entity_id: climate.craft_room
    type: set_hvac_mode
    hvac_mode: cool
  mode: single
- id: '1657809251650'
  alias: UPS Turn Off lights after blip
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.ups_trap
    to: 'UPS: No longer on battery power.'
  condition: []
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      entity_id:
      - light.sengled_e11_g13_035cb3f8_1
      - light.sengled_e11_g13_035c3bc7_1
      - light.bed_wled
      - light.wink_bed_room
      - light.wink_led_strip_bath
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: homeassistant.turn_off
    data: {}
    target:
      entity_id:
      - light.sengled_e11_g13_035cb3f8_1
      - light.sengled_e11_g13_035c3bc7_1
      - light.bed_wled
      - light.wink_bed_room
      - light.wink_led_strip_bath
  mode: single
- id: '1665261527952'
  alias: New Automation
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.nodered_adb232849e46f6ef
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 10
    target:
      entity_id: light.bed_wled
  mode: single
- id: '1665668429834'
  alias: Door Alerts v2
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_entry_door, binary_sensor.wink_front_door_opened,
      binary_sensor.wink_back_door_opened, binary_sensor.basement_door, binary_sensor.front_door
    to: 'on'
  condition:
  - condition: state
    entity_id: group.device_family
    state: home
  action:
  - wait_template: '{% set new = trigger.entity_id %} {{ is_state(new, ''off'') }}

      '
    timeout: 00:00:10
  - service: notify.telegram_ryan
    data:
      message: "{% set new = trigger.entity_id %} {% if is_state(new, 'off') %}\n
        \ {{ trigger.to_state.name }} was opened and closed.\n{% else %}\n  {{ trigger.to_state.name
        }} was opened.\n{% endif %}\n"
  - condition: template
    value_template: '{% set new = trigger.entity_id %} {{ is_state(new, ''on'') }}

      '
  - wait_template: '{% set new = trigger.entity_id %} {{ is_state(new, ''off'') }}

      '
  - service: notify.telegram_ryan
    data:
      message: '{{ trigger.to_state.name }} was closed

        '
  mode: parallel
  max: 10
- id: '1665711480975'
  alias: Climate -  Auto Craft Cool
  description: ''
  trigger:
  - platform: template
    value_template: '{{states.climate.craft_room.attributes.current_temperature >
      states.climate.craft_room.attributes.temperature or states.climate.craft_room.attributes.current_temperature
      < states.climate.craft_room.attributes.temperature-1}}

      '
    for:
      minutes: 5
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{states.climate.craft_room.attributes.current_temperature
          < states.climate.craft_room.attributes.temperature-1}}'
      sequence:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: 'off'
        target:
          entity_id: climate.craft_room
    - conditions:
      - condition: template
        value_template: '{{states.climate.craft_room.attributes.current_temperature
          > states.climate.craft_room.attributes.temperature}}'
      sequence:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: cool
        target:
          entity_id: climate.craft_room
  mode: single
- id: '1665711964366'
  alias: Climate - Auto Office Heat
  description: ''
  trigger:
  - platform: template
    value_template: '{{states.climate.bed_room.attributes.current_temperature > states.climate.bed_room.attributes.temperature
      or states.climate.bed_room.attributes.current_temperature < states.climate.bed_room.attributes.temperature-1}}

      '
    for:
      minutes: 5
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{states.climate.bed_room.attributes.current_temperature
          < states.climate.bed_room.attributes.temperature-1}}'
      sequence:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: heat
        target:
          entity_id:
          - climate.bed_room
    - conditions:
      - condition: template
        value_template: '{{states.climate.bed_room.attributes.current_temperature
          > states.climate.bed_room.attributes.temperature}}'
      sequence:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: 'off'
        target:
          entity_id:
          - climate.bed_room
  mode: single
- id: '1665712050949'
  alias: Climate - Auto Craft Heat
  description: ''
  trigger:
  - platform: template
    value_template: '{{states.climate.craft_room.attributes.current_temperature >
      states.climate.craft_room.attributes.temperature or states.climate.craft_room.attributes.current_temperature
      < states.climate.craft_room.attributes.temperature-1}}

      '
    for:
      minutes: 5
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{states.climate.craft_room.attributes.current_temperature
          < states.climate.craft_room.attributes.temperature-1}}'
      sequence:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: heat
        target:
          entity_id: climate.craft_room
    - conditions:
      - condition: template
        value_template: '{{states.climate.craft_room.attributes.current_temperature
          > states.climate.craft_room.attributes.temperature}}'
      sequence:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: 'off'
        target:
          entity_id: climate.craft_room
  mode: single
- id: '1666117827132'
  alias: upstairs dimmer
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: 50b370ca9c6b4fcf91f0fee0cb747b7b
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{trigger.event.data.params.level == 2}}'
      sequence:
      - service: light.turn_off
        data: {}
        target:
          entity_id:
          - light.sengled_e11_g13_035cb3f8_1
          - light.sengled_e11_g13_035c3bc7_1
    default:
    - service: light.turn_on
      data:
        brightness: '{{trigger.event.data.params.level | int}}'
        transition: 1
      target:
        entity_id:
        - light.sengled_e11_g13_035c3bc7_1
        - light.sengled_e11_g13_035cb3f8_1
  mode: restart
- id: '1666123844519'
  alias: bed light dimmer
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      unique_id: ff:ff:00:0f:e7:fd:89:a4:1:0x0008
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{trigger.event.data.params.level == 2}}'
      sequence:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.bed_wled
    default:
    - service: light.turn_on
      data:
        brightness: '{{trigger.event.data.params.level | int}}'
        transition: 1
      target:
        entity_id:
        - light.bed_wled
  mode: restart
- id: '1667065340558'
  alias: HCPSS Status Changes
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.hcps_status
  condition: []
  action:
  - service: notify.telegram_group
    data:
      message: '✏HCPSS is: {{trigger.to_state.state}}✏'
  mode: single
- id: '1667065431239'
  alias: Blue Iris Status
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.blueiris
  condition: []
  action:
  - service: notify.telegram_ryan
    data:
      message: "\U0001F4F9Blue Iris: {{trigger.to_state.state}}\U0001F4F9"
  mode: single
- id: '1667183802979'
  alias: Hot Water
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
    id: 'off'
  - platform: time
    at: '17:00:00'
    id: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: 'off'
      - condition: and
        conditions:
        - condition: state
          entity_id: group.device_family
          state: not_home
        - condition: state
          entity_id: input_boolean.house_guest
          state: 'off'
        - condition: state
          entity_id: switch.wink_zwaveoutlet
          state: 'on'
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.wink_zwaveoutlet
    - conditions:
      - condition: trigger
        id: 'on'
      - condition: state
        entity_id: switch.wink_zwaveoutlet
        state: 'off'
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.wink_zwaveoutlet
  mode: single
- id: '1667185001857'
  alias: Vacation Lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:38:00
    id: living room on
  - platform: sun
    event: sunset
    offset: +01:00:00
    id: living room off
  - platform: sun
    event: sunset
    offset: +01:40:00
    id: bed room on
  - platform: sun
    event: sunset
    offset: +03:25:00
    id: bed room off
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: living room on
      sequence:
      - service: homeassistant.turn_on
        data: {}
        target:
          entity_id: switch.wink_hallway_switch
    - conditions:
      - condition: trigger
        id: living room off
      sequence:
      - service: homeassistant.turn_off
        data: {}
        target:
          entity_id: switch.wink_hallway_switch
    - conditions:
      - condition: trigger
        id: bed room on
      sequence:
      - service: homeassistant.turn_on
        data: {}
        target:
          entity_id: light.wink_bed_room
    - conditions:
      - condition: trigger
        id: bed room off
      sequence:
      - service: homeassistant.turn_off
        data: {}
        target:
          entity_id: light.wink_bed_room
  mode: single
- id: '1667185720938'
  alias: No one is home , turn the lights on
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: state
    entity_id: group.device_family
    state: not_home
  - condition: state
    entity_id: input_boolean.house_guest
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: homeassistant.turn_on
    data: {}
    target:
      entity_id:
      - switch.wink_front_porch_switch
      - switch.powerpivot1_2
      - switch.powerpivot1_1
      - switch.wink_hallway_switch
  - service: notify.telegram_group
    data:
      message: No one is home so i turned on some lights
  mode: single
