homeassistant:
  name: LilOld
  latitude: !secret lat
  longitude: !secret long
  currency: USD
  elevation: 186
  unit_system: imperial
  time_zone: America/New_York
  temperature_unit: F
  customize: !include customize.yaml
  customize_domain: {}
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password
    - type: trusted_networks
      trusted_networks:
        - 192.168.47.0/24
        - 10.0.93.2/32

default_config:
zeroconf:
mobile_app:

# Enables the frontend
frontend:
  themes: !include includes/themes.yaml

map:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
  intents:
    turnonoff:
    - Turn [on] [off] [the] {light} [light] [switch]

# enables the config panel
config:
   
# This is the history tab (Graphs) you can hide certain components.
history:
  exclude:
    domains:
      - automation
      - group
      - alert
    entities:
      - sensor.time

# Track the sun
sun:

#shell_command:


media_player:
#  - platform: androidtv
#    name: Fire TV 1
#    host: 192.168.47.215
#    adbkey: !secret adbkey


system_health:


logger:
 default: warn
 logs:
#   urllib3.connectionpool: fatal
#   homeassistant.components.http: debug
#   homeassistant.core: debug
#   pubnubsubhandler: info
#   pywink.api: debug
#   homeassistant.components.wink: debug
#   homeassistant.components.notify.ios: debug
   requests.packages.urllib3.connectionpool: fatal
   homeassistant.components.camera: error


################################################
## Component Includes (Merge List)
################################################

#fan: !include includes/fans.yaml
#hangouts: !include includes/hangouts.yaml
#influxdb: !include includes/influxdb.yaml
alert: !include includes/alert.yaml
automation old: !include_dir_merge_list includes/automation/
automation: !include automations.yaml
binary_sensor: !include includes/binary_sensor.yaml
climate: !include includes/climates.yaml
cloud: !include includes/cloud.yaml
device_tracker: !include includes/device_tracker.yaml
group: !include includes/group.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_select: !include includes/input_select.yaml
intent_script: !include includes/intent_scripts.yaml
light: !include includes/light.yaml
logbook: !include includes/logbook.yaml
notify: !include includes/notify.yaml
panel_iframe: !include includes/iframe.yaml
recorder: !include includes/recorder.yaml
scene: !include includes/scene.yaml
script: !include scripts.yaml
sensor templates: !include includes/sensor_templates.yaml
sensor: !include includes/sensor.yaml
switch: !include includes/switch.yaml
zone: 
ios: !include includes/ios.yaml


#python_script:

tts:
  - platform: google_translate
    service_name: google_say
  
alexa:
  
telegram_bot:
  - platform: polling
    api_key: !secret telegram
    parse_mode: html
    allowed_chat_ids:
     - 618533989
     - 664122562
     - 356616190
     - -356616190
     - -543668285
 
shopping_list:
      
stream:
  
twilio:
  account_sid: !secret ACCOUNT_SID_FROM_TWILIO
  auth_token: !secret AUTH_TOKEN_FROM_TWILIO
  
# Example configuration.yaml entry
weather:
  - platform: template
    name: "my ws"
    condition_template: "{{ states('weather.home')}}"
    temperature_template: "{{ states('sensor.pws_5in1_temperature') | float}}" 
    humidity_template: "{{ states('sensor.pws_5in1_humidity')| float }}"
    forecast_template: "{{ states.weather.home.attributes.forecast }}"
    wind_speed_template: "{{ states('sensor.pws_5in1_wind')| float }}"


opnsense:
  url: !secret fw
  api_secret: !secret fw_secret
  api_key: !secret fw_key