homeassistant:
  # Name of the location where Home Assistant is running
  name: LilOld
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data
  elevation: 186
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  temperature_unit: F
  customize: !include includes/customize.yaml
  customize_domain: {}
  customize_glob:
    # "automation.*":
    # "group.*":
    # "switch.*":
    # "cover.*":
    # "light.*":
    # "script.*":
    # "scene.*":
    # "device_tracker.*":
    "input_boolean.*":
      persistent: true
    "input_number.*":
      persistent: true
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
    - type: trusted_networks

zeroconf:

cast: 

# Enables the frontend
frontend:
  themes: !include includes/themes.yaml

map:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
  intents:
    turnonoff:
    - Turn [on] [off] [the] {light} [light] [switch]
    

# enables the config panel
config:

# Records states to the database
   
# This is the history tab (Graphs) you can hide certain components.
history:
  exclude:
    domains:
      - automation
      - group
    entities:
      - sensor.time

# Track the sun
sun:

ifttt:
  key: !secret ifttt_key

ifttt2:
  key: !secret ifttt_key2
    
mqtt:
  broker: 192.168.47.202
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant

alarm_control_panel:
  platform: manual
  name: "HA Alarm"
  code: !secret alarm_passcode
  pending_time: 60
  trigger_time: 120
  disarm_after_trigger: true

shell_command:
  call_chelsea: /root/.homeassistant/scripts/call_chelsea.sh
  call_ryan: /root/.homeassistant/scripts/.sh
  restart_drivewaycam: /root/port_bounce.sh
  update_config: /root/.homeassistant/bin/pull_from_github.sh

media_player:
  - platform: firetv
    name: Fire TV 1
    host: 192.168.47.134
    adbkey: !secret adbkey
#  - platform: alexa
#    email: nevar
#    password: never
#    url: amazon.com
#  - platform: cast
#  - platform: kodi
#    host: kodi-garage.
#    username: kodi
#    password: never
#    name: kodi_garage

logger:
 default: warning
 logs:
   urllib3.connectionpool: fatal
   homeassistant.components.http: debug
#   homeassistant.core: debug
#   pubnubsubhandler: info
#   pywink.api: debug
#   homeassistant.components.wink: debug
   requests.packages.urllib3.connectionpool: fatal
#  pyicloud.base: debug
#  homeassistant.components.device_tracker.icloud: debug
   homeassistant.components.camera: error
   homeassistant.components.image_processing.openalpr_cloud: debug
   homeassistant.components.http.view: warn

################################################
## Component Includes (Merge List)
################################################

automation: !include automations.yaml
automation old: !include_dir_merge_list includes/automation/
group: !include includes/group.yaml
switch: !include includes/switch.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensor.yaml
binary_sensor: !include includes/binary_sensor.yaml
sensor templates: !include includes/sensor_templates.yaml
zone: !include includes/zone.yaml
panel_iframe: !include includes/iframe.yaml
scene: !include includes/scene.yaml
input_select: !include includes/input_select.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
cover: !include includes/cover.yaml
device_tracker: !include includes/device_tracker.yaml
intent_script: !include includes/intent_scripts.yaml
#fan: !include includes/fans.yaml
notify: !include includes/notify.yaml
alert: !include includes/alert.yaml
cloud: !include includes/cloud.yaml
recorder: !include includes/recorder.yaml
logbook: !include includes/logbook.yaml
#hangouts: !include includes/hangouts.yaml

#wink_lc_service:
#  key: !secret wink_lc_key
#  host: 192.168.47.157

climate:
  - platform: generic_thermostat
    name: Brooder
    heater: switch.wifi_switch1
    target_sensor: sensor.sn3_temperature
    cold_tolerance: 1.0
    hot_tolerance: 1.0
    initial_operation_mode: "auto"
  - platform: generic_thermostat
    name: Chicken Fan
    heater: switch.esp3
    target_sensor: sensor.sn2_temperature
    cold_tolerance: 1.0
    hot_tolerance: 1.0
    initial_operation_mode: "auto"
    ac_mode: true
    target_temp: 80
    min_cycle_duration:
      minutes: 5
    
tts:
  - platform: google
  
alexa:
 
light:  
  - platform: mqtt
    schema: json
    name: "SN1 LED"  
    state_topic: "home/sensornode1"  
    command_topic: "home/sensornode1/set"  
    brightness: true  
    flash: true  
    rgb: true  
    optimistic: false  
    qos: 0 
  - platform: mqtt
    schema: json
    name: "SN2 LED"  
    state_topic: "home/sensornode2"  
    command_topic: "home/sensornode2/set"  
    brightness: true  
    flash: true  
    rgb: true  
    optimistic: false  
    qos: 0 

#emulated_hue:
#  expose_by_default: false
  
influxdb:
  host: 192.168.47.155
  port: 8086
  max_retries: 10
  
homekit:
  auto_start: False
  filter:
    include_domains:
      - light
      - cover
      - switch
  
telegram_bot:
  - platform: polling
    api_key: !secret telegram
    parse_mode: html
    allowed_chat_ids:
     - 618533989
     - 664122562
     - 356616190
     - -356616190
 
shopping_list:

