homeassistant:
  # Name of the location where Home Assistant is running
  name: LilOld
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data
  elevation: 186
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  temperature_unit: F
  customize: !include customize.yaml
  customize_domain: {}
  customize_glob:
    "automation.*":
       persistent: true
    # "group.*":
    # "switch.*":
    # "cover.*":
    # "light.*":
    # "script.*":
    # "scene.*":
    # "device_tracker.*":
    "input_boolean.*":
      persistent: true
    "input_number.*":
      persistent: true
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password
    - type: trusted_networks
      trusted_networks:
        - 192.168.47.0/24
        - 10.0.93.2/32

default_config:
zeroconf:
mobile_app:

# Enables the frontend
frontend:
  themes: !include includes/themes.yaml

map:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
  intents:
    turnonoff:
    - Turn [on] [off] [the] {light} [light] [switch]
    

# enables the config panel
config:

# Records states to the database
   
# This is the history tab (Graphs) you can hide certain components.
history:
  exclude:
    domains:
      - automation
      - group
      - alert
    entities:
      - sensor.time

# Track the sun
sun:
    
mqtt:
  broker: !secret mqtt_url
  port: 1883
  username: homeassistant-broker
  password: !secret http_password
  client_id: home-assistant-1
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant

#shell_command:


media_player:
#  - platform: androidtv
#    name: Fire TV 1
#    host: 192.168.47.215
#    adbkey: !secret adbkey


system_health:


logger:
 default: info
 logs:
#   urllib3.connectionpool: fatal
#   homeassistant.components.http: debug
#   homeassistant.core: debug
#   pubnubsubhandler: info
#   pywink.api: debug
#   homeassistant.components.wink: debug
#   homeassistant.components.notify.ios: debug
   requests.packages.urllib3.connectionpool: fatal
#  pyicloud.base: debug
#  homeassistant.components.device_tracker.icloud: debug
   homeassistant.components.camera: error
#   homeassistant.components.image_processing.openalpr_cloud: debug
#   homeassistant.components.http.view: warn
# for v 1.0.0
#   custom_components.alexa_media: debug  
# for API debugging (verbose and intended for service debugging)
#   alexapy: debug

################################################
## Component Includes (Merge List)
################################################

#fan: !include includes/fans.yaml
#hangouts: !include includes/hangouts.yaml
#influxdb: !include includes/influxdb.yaml
alert: !include includes/alert.yaml
automation old: !include_dir_merge_list includes/automation/
automation: !include automations.yaml
binary_sensor: !include includes/binary_sensor.yaml
climate: !include includes/climates.yaml
cloud: !include includes/cloud.yaml
cover: !include includes/cover.yaml
device_tracker: !include includes/device_tracker.yaml
group: !include includes/group.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_select: !include includes/input_select.yaml
intent_script: !include includes/intent_scripts.yaml
light: !include includes/light.yaml
logbook: !include includes/logbook.yaml
notify: !include includes/notify.yaml
panel_iframe: !include includes/iframe.yaml
recorder: !include includes/recorder.yaml
scene: !include includes/scene.yaml
script: !include scripts.yaml
sensor templates: !include includes/sensor_templates.yaml
sensor: !include includes/sensor.yaml
switch: !include includes/switch.yaml
zone: 


#python_script:

tts:
  - platform: google_translate
    service_name: google_say
  
alexa:
  
telegram_bot:
  - platform: polling
    api_key: !secret telegram
    parse_mode: html
    allowed_chat_ids:
     - 618533989
     - 664122562
     - 356616190
     - -356616190
     - -543668285
 
shopping_list:

google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret
      
stream:
  
twilio:
  account_sid: !secret ACCOUNT_SID_FROM_TWILIO
  auth_token: !secret AUTH_TOKEN_FROM_TWILIO
  
# Example configuration.yaml entry
weather:
  - platform: template
    name: "my ws"
    condition_template: "{{ states('weather.home')}}"
    temperature_template: "{{ states('sensor.pws_5in1_temperature') | float}}" 
    humidity_template: "{{ states('sensor.pws_5in1_humidity')| float }}"
    forecast_template: "{{ states.weather.home.attributes.forecast }}"
    wind_speed_template: "{{ states('sensor.pws_5in1_wind')| float }}"
