# Enable logging
logger:

# Enable Home Assistant API
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

web_server:
  port: 80

switch:
  - platform: template
    name: "Chicken Pen Door Status"
    id: pen_door_status
    optimistic: true

binary_sensor:
  - platform: status
    name: "Chicken Sensor"


    
