substitutions:
  name: rat_firstbay-11e249
  friendly_name: First Bay 11e249
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard_secplusv1.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: ufS8TOgP00Ytncc/ORKQDZ3C0YoOCqj7oq1Sbv7FLd0=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
