substitutions:
  name: rat_thirdbay-11d3bf
  friendly_name: Third Bay 11d3bf
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard_secplusv1.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: Ndt8pVK4Yd7dMdUxtU/weGFel7AblcZs3F8qIUhrJNU=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
