#- platform: command_line
#  command: ps -p $(cat /root/dasher/pid/dasher.pid) > /dev/null && (echo "Running") || (echo "Not running")
#  name: 'dasher'
#  sensor_class: moving
#  payload_on: "Running"
#  payload_off: "Not running"
  
- platform: template
  sensors:
    climate_aux_heat:
      value_template: "{{ states.climate.home.attributes.aux_heat == 'on' }}"
      friendly_name: 'Aux Heat'
    climate_fan:
      value_template: "{{ states.climate.home.attributes.fan == 'on' }}"
      friendly_name: 'Fan'
    chicken_door_after_dark:
      value_template: '{{ is_state("cover.chicken_door", "open") and states.sensor.time.state > states.sensor.chicken_door_last_call_time_dirty.state and is_state("input_boolean.chicken_door_last_call", "off") }}'
    still_dark:
      value_template: '{{ states.sun.sun.attributes.elevation < -6 }}'
    chicken_door_after_open:
      value_template: '{{ is_state("cover.chicken_door", "closed") and is_state("sun.sun", "above_horizon") and states.sensor.time.state > states.sensor.chicken_door_time.state}}'
    alarm_is_pending_triggered:
      value_template: '{{states.alarm_control_panel.ha_alarm.attributes.post_pending_state == "triggered" }}'
    alarm_is_pending:
      value_template: '{{states.alarm_control_panel.ha_alarm.state == "pending" }}'
    template_wink_hub:
      value_template: '{{ is_state("binary_sensor.wink_hub", "on")}}'
    template_disk_space:
      value_template: '{{states.sensor.disk_use_percent_.state |int > 90}}'
- platform: trend
  sensors:
    temperature_up:
      friendly_name: 'Temp increasing'
      entity_id: sensor.sn3_temperature
      device_class: heat
    temperature_down:
      friendly_name: 'Temp decreasing'
      entity_id: sensor.sn3_temperature
      device_class: cold
      invert: Yes
    house_temperature_up:
      friendly_name: 'Temp increasing'
      entity_id: sensor.home_temperature
      device_class: heat
    house_temperature_down:
      friendly_name: 'Temp decreasing'
      entity_id: sensor.home_temperature
      device_class: cold
      invert: Yes
#######################################################
## blue iris
#######################################################
- platform: mqtt
  state_topic: "Blueiris/z238/status"
  name: "Chicken Coop Motion"

- platform: mqtt  
  state_topic: "stat/sonoff_basement/POWER"  
  name: "front_door" 
  device_class: door
  availability_topic: "tele/sonoff_basement/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  
- platform: mqtt
  name: "OpenMQTTGateway"
  state_topic: "home/OpenMQTTGateway/LWT"
  payload_on: "Online"
  payload_off: "Offline"
  device_class: "connectivity"