- platform: trend
  sensors:
#    trend_house_temperature_up:
#      friendly_name: 'Temp increasing'
#      entity_id: sensor.home_temperature
#      device_class: heat
    trend_house_temperature_down:
      friendly_name: 'Temp decreasing'
      entity_id: sensor.home_temperature
      device_class: cold
      invert: Yes
      max_samples: 8
#    trend_outside_temperature_up:
#      friendly_name: 'Outside Temp increasing'
#      entity_id: sensor.pws_5in1_temperature
#      device_class: heat
    trend_outside_temperature_down:
      friendly_name: 'Outisde Temp decreasing'
      entity_id: sensor.pws_5in1_temperature
      device_class: cold
      invert: Yes
      max_samples: 8
#    trend_stove_temperature_up:
#      friendly_name: 'Stove Temp increasing'
#      entity_id: sensor.air_output_sensor
#      device_class: heat
    trend_stove_temperature_down:
      friendly_name: 'Stove Temp decreasing'
      entity_id: sensor.air_output_sensor
      device_class: cold
      invert: Yes
      max_samples: 4
    trend_flue_temperature_down:
      friendly_name: 'Stove Flue decreasing'
      entity_id: sensor.woodstove_flue_temperature
      device_class: cold
      invert: Yes
      max_samples: 4


- platform: bayesian
  prior: 0.33
  name: 'Bayesian Sleeping'
  probability_threshold: 0.80
  observations:
      - entity_id: 'group.device_family'
        prob_given_true: 0.99
        prob_given_false: 0.56
        platform: 'state'
        to_state: 'home'
      - entity_id: 'sun.sun'
        prob_given_true: 0.75
        prob_given_false: 0.31
        platform: 'state'
        to_state: 'below_horizon'
      - entity_id: 'group.indoor_lights'
        prob_given_true: 0.9
        prob_given_false: 0.5
        platform: 'state'
        to_state: 'off'
      # - entity_id: 'sensor.coffeemaker'
        # prob_given_true: 0.8
        # prob_given_false: 0.4
        # platform: 'state'
        # to_state: 'Ready'
      # - entity_id: 'variable.last_motion'
        # prob_given_true: 0.9
        # prob_given_false: 0.3
        # platform: 'state'
        # to_state: 'Bathroom Motion'
      - entity_id: 'sensor.fry_battery_state'
        prob_given_true: 0.25
        prob_given_false: 0.75
        platform: 'state'
        to_state: 'Not Charging'
