- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time_iso'

# - platform: cert_expiry
  # host: !secret ha_cert 
  
# - platform: cert_expiry
  # host: !secret nginz_cert 
  
- platform: history_stats
  name: history_climate_fan_on_today
  entity_id: binary_sensor.climate_fan
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
  scan_interval: 60
  
- platform: history_stats
  name: history_climate_cool_on_today
  entity_id: sensor.climate_operation
  state: 'cooling'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
  scan_interval: 60
  
- platform: history_stats
  name: history_climate_heat_on_today
  entity_id: sensor.climate_operation
  state: 'heating'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
  scan_interval: 60
  
- platform: history_stats
  name: history_climate_aux_heat_on_today
  entity_id: binary_sensor.climate_aux_heat
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
  scan_interval: 60
 
- platform: snmp
  name: Garage Temp
  host: 192.168.47.238
  port: 161
  accept_errors: true
  community: public
  baseoid: 1.3.6.1.4.1.21239.2.2.1.6.1
  unit_of_measurement: "°F"
  
- platform: snmp   
  name: Garage Humidity
  host: 192.168.47.238
  port: 161
  accept_errors: true
  community: public
  baseoid: 1.3.6.1.4.1.21239.2.2.1.7.1
  unit_of_measurement: "%"

- platform: snmp
  name: Basement Temp
  host: 192.168.47.123
  port: 161
  accept_errors: true
  community: bittner
  baseoid: 1.3.6.1.4.1.21239.2.2.1.6.1
  unit_of_measurement: "°F"
  
- platform: snmp   
  name: Basement Humidity
  host: 192.168.47.123
  port: 161
  accept_errors: true
  community: bittner
  baseoid: 1.3.6.1.4.1.21239.2.2.1.7.1
  unit_of_measurement: "%"
  
- platform: statistics
  name: Local Rain 24 Hours Statistics
  entity_id: sensor.pws_5in1_total_rain
  state_characteristic: change
  sampling_size: 4320 # Enough for 3 readings a minute
  max_age:
    hours: 24
- platform: statistics
  name: Local Rain 1 Hours Statistics
  entity_id: sensor.pws_5in1_total_rain
  state_characteristic: change
  sampling_size: 2000 # Enough for 3 readings a minute
  max_age:
    hours: 1
- platform: statistics
  name: Peak Wind Speed
  entity_id: sensor.pws_5in1_wind
  state_characteristic: value_max
  sampling_size: 2000 # Enough for 3 readings a minute
  max_age:
    hours: 1
- platform: statistics
  name: Average Wind Speed
  entity_id: sensor.pws_5in1_wind
  state_characteristic: mean
  sampling_size: 2000 # Enough for 3 readings a minute
  max_age:
    minutes: 2
- platform: statistics
  name: Lowest temp last 12 hr
  entity_id: sensor.pws_5in1_temperature
  state_characteristic: value_min
  sampling_size: 20000 # Enough for 3 readings a minute
  max_age:
    hours: 12
- platform: statistics
  name: Highest Temp Last 12 hr
  entity_id: sensor.pws_5in1_temperature
  state_characteristic: value_max
  sampling_size: 20000 # Enough for 3 readings a minute
  max_age:
    hours: 12

- platform: integration
  name: Closet Energy
  source: sensor.ups_power_usage
  unit_prefix: k

