- platform: orvibo
  discovery: false
  switches:
    - host: 192.168.47.208
      name: "Wifi Switch1"

- platform: mqtt
  name: "esp1"
  unique_id: esp1
  state_topic: "home/sonoff/1/1/stat"
  command_topic: "home/sonoff/1/1"
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true
- platform: mqtt
  name: "esp2"
  unique_id: esp2
  state_topic: "home/sonoff/2/1/stat"
  command_topic: "home/sonoff/2/1"
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true
- platform: mqtt
  name: "esp3"
  unique_id: esp3
  state_topic: "stat/esp3/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp3/POWER"
  availability_topic: "tele/esp3/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: true
- platform: mqtt
  name: "esp4"
  unique_id: esp4
  state_topic: "stat/esp4/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp4/POWER"
  availability_topic: "tele/esp4/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: true
- platform: mqtt
  unique_id: esp5
  name: "esp5"
  state_topic: "home/sonoff/5/1/stat"
  command_topic: "home/sonoff/5/1"
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true
- platform: mqtt
  unique_id: esp6
  name: "esp6"
  state_topic: "home/sonoff/6/1/stat"
  command_topic: "home/sonoff/6/1"
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true
- platform: mqtt
  name: "On/Off Sonoff"
  state_topic: "stat/sonoffdual/RESULT"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/sonoffdual/POWER1"
  availability_topic: "tele/sonoffdual/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "On/Off Sonoff2"
  state_topic: "stat/sonoffdual/RESULT"
  value_template: '{{ value_json["POWER2"] }}'
  command_topic: "cmnd/sonoffdual/POWER2"
  availability_topic: "tele/sonoffdual/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: template
  switches:
    wink_siren2:
      value_template: "{{ is_state('wink.siren2', 'on') }}"
      turn_on:
        service: wink.enable_siren
        data:
          entity_id: wink.siren2
          enabled: true
      turn_off:
        service: wink.enable_siren
        data:
          entity_id: wink.siren2
          enabled: false
    wink_siren1:
      value_template: "{{ is_state('wink.siren1', 'on') }}"
      turn_on:
        service: wink.enable_siren
        data:
          entity_id: wink.siren1
          enabled: true
      turn_off:
        service: wink.enable_siren
        data:
          entity_id: wink.siren1
          enabled: false

- platform: mqtt
  name: "PowerPivot1-1"
  state_topic: "stat/powerpivot1/RESULT"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/powerpivot1/POWER1"
  availability_topic: "tele/powerpivot1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true 

- platform: mqtt
  name: "PowerPivot1-2"
  state_topic: "stat/powerpivot1/RESULT"
  value_template: '{{ value_json["POWER2"] }}'
  command_topic: "cmnd/powerpivot1/POWER2"
  availability_topic: "tele/powerpivot1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "PowerPivot2-1"
  state_topic: "stat/powerpivot2/RESULT"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/powerpivot2/POWER1"
  availability_topic: "tele/powerpivot2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true 

- platform: mqtt
  name: "PowerPivot2-2"
  state_topic: "stat/powerpivot2/RESULT"
  value_template: '{{ value_json["POWER2"] }}'
  command_topic: "cmnd/powerpivot2/POWER2"
  availability_topic: "tele/powerpivot2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Side Spigot"
  state_topic: "stat/Jinvoo/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/Jinvoo/POWER"
  availability_topic: "tele/Jinvoo/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true 
  
- platform: mqtt
  name: "4chpro 1"
  state_topic: "stat/sonoff4chpro/RESULT"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/sonoff4chpro/POWER1"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "4chpro 2"
  state_topic: "stat/sonoff4chpro/RESULT"
  value_template: '{{ value_json["POWER2"] }}'
  command_topic: "cmnd/sonoff4chpro/POWER2"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "4chpro 3"
  state_topic: "stat/sonoff4chpro/RESULT"
  value_template: '{{ value_json["POWER3"] }}'
  command_topic: "cmnd/sonoff4chpro/POWER3"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "4chpro 4"
  state_topic: "stat/sonoff4chpro/RESULT"
  value_template: '{{ value_json["POWER4"] }}'
  command_topic: "cmnd/sonoff4chpro/POWER4"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Bathroom Fan"
  state_topic: "stat/esp_bathroom/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp_bathroom/POWER"
  availability_topic: "tele/esp_bathroom/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  #retain: true 
  optimistic: true
- platform: mqtt
  name: "Traffic Light Green"
  state_topic: "stat/trafficlight/RESULT"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/trafficlight/POWER1"
  availability_topic: "tele/trafficlight/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Traffic Light Yellow"
  state_topic: "stat/trafficlight/RESULT"
  value_template: '{{ value_json["POWER2"] }}'
  command_topic: "cmnd/trafficlight/POWER2"
  availability_topic: "tele/trafficlight/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Traffic Light Red"
  state_topic: "stat/trafficlight/RESULT"
  value_template: '{{ value_json["POWER3"] }}'
  command_topic: "cmnd/trafficlight/POWER3"
  availability_topic: "tele/trafficlight/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
#################################################
#### ROUND
#################################################
- platform: mqtt
  name: "Round 1"
  state_topic: "stat/round/RESULT"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/round/POWER1"
  availability_topic: "tele/round/LWT"
  unique_id: round1
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Round 2"
  unique_id: round2
  state_topic: "stat/round/RESULT"
  value_template: '{{ value_json["POWER2"] }}'
  command_topic: "cmnd/round/POWER2"
  availability_topic: "tele/round/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Round 3"
  unique_id: round3
  state_topic: "stat/round/RESULT"
  value_template: '{{ value_json["POWER3"] }}'
  command_topic: "cmnd/round/POWER3"
  availability_topic: "tele/round/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "esp7"
  unique_id: esp7
  state_topic: "stat/esp7/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp7/POWER"
  availability_topic: "tele/esp7/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "esp8"
  unique_id: esp8
  state_topic: "stat/esp8/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp8/POWER"
  availability_topic: "tele/esp8/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "esp9"
  unique_id: esp9
  state_topic: "stat/esp9/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp9/POWER"
  availability_topic: "tele/esp8/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
