- platform: orvibo
  discovery: false
  switches:
    - host: 192.168.47.208
      name: "Wifi Switch1"
      
#- platform: command_line
#  switches:
#      frontporch_lc:
#       command_on: "curl -X PUT -k -H \"Authorization: Bearer 28b5ae18ea1fff4a6f9220a224efad40\" -H \"Content-Type: application/json\" -d '{\"desired_state\":{\"powered\":true}}' https://192.168.47.157:8888/lights/5"
#       command_off: "curl -X PUT -k -H \"Authorization: Bearer 28b5ae18ea1fff4a6f9220a224efad40\" -H \"Content-Type: application/json\" -d '{\"desired_state\":{\"powered\":false}}' https://192.168.47.157:8888/lights/5"
#      floodlight_lc:
#       command_on: "curl -X PUT -k -H \"Authorization: Bearer 28b5ae18ea1fff4a6f9220a224efad40\" -H \"Content-Type: application/json\" -d '{\"desired_state\":{\"powered\":true}}' https://192.168.47.157:8888/lights/7"
#       command_off: "curl -X PUT -k -H \"Authorization: Bearer 28b5ae18ea1fff4a6f9220a224efad40\" -H \"Content-Type: application/json\" -d '{\"desired_state\":{\"powered\":false}}' https://192.168.47.157:8888/lights/7"

#    frontporch_lc1:
#     command_on: '/root/wink.sh "-m5 -u -t1 -vON"'
#     command_off: '/root/wink.sh "-m5 -u -t1 -vOFF"'
#     command_state: "/root/wink.sh '-m5 -l | grep \"^           1\" | cut -d \"|\" -f 5 | xargs | grep ON'"
     #value_template: '{{ is_state("light.wink_front_porch", "on") }}'
#    floodlight_lc1:
#     command_on: "/root/wink.sh '-m7 -u -t1 -vON'"
#     command_off: "/root/wink.sh '-m7 -u -t1 -vOFF'"
#     command_state: "/root/wink.sh '-m7 -l | grep \"^           2\" | cut -d \"|\" -f 5 | xargs | grep TRUE'"
#       value_template: "{{ is_state('switch.wink_back_flood', 'on') }}"

#  - platform: template
#    switches:
#     frontporch_tmp:
#      value_template: '{{ is_state("light.wink_front_porch", "on") or is_state("switch.frontporch_lc1", "on") }}'
#      turn_on:
#       service: homeassistant.turn_on
#       entity_id: switch.frontporch_lc1, light.wink_front_porch
#      turn_off:
#       service: homeassistant.turn_off
#       entity_id: switch.frontporch_lc1, light.wink_front_porch
#      entity_id: light.wink_front_porch, switch.frontporch_lc1
#  - platform: template
#    switches:
#     flood_tmp:
#      value_template: '{{ is_state("switch.wink_back_flood", "on") or is_state("switch.floodlight_lc1", "on") }}'
#     turn_on:
#       service: homeassistant.turn_on
#       entity_id: switch.floodlight_lc1, switch.wink_back_flood
#      turn_off:
#       service: homeassistant.turn_off
#       entity_id: switch.wink_back_flood, switch.floodlight_lc1
#      entity_id: switch.wink_back_flood, switch.floodlight_lc1

- platform: mqtt
  name: "esp1"
  state_topic: "home/sonoff/1/1/stat"
  command_topic: "home/sonoff/1/1"
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true
- platform: mqtt
  name: "esp2"
  state_topic: "home/sonoff/2/1/stat"
  command_topic: "home/sonoff/2/1"
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true
- platform: mqtt
  name: "esp3"
  state_topic: "stat/esp3/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp3/POWER"
  availability_topic: "tele/esp3/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: true
- platform: mqtt
  name: "esp4"
  state_topic: "stat/esp4/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp4/POWER"
  availability_topic: "tele/esp4/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: true
- platform: mqtt
  name: "esp5"
  state_topic: "home/sonoff/5/1/stat"
  command_topic: "home/sonoff/5/1"
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true
- platform: mqtt
  name: "esp6"
  state_topic: "home/sonoff/6/1/stat"
  command_topic: "home/sonoff/6/1"
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true
- platform: mqtt
  name: "sensornode2_relay1"
  state_topic: "home/sensornode2/relay1"
  command_topic: "home/sensornode2/relay1/set/"
  payload_on: "1"
  payload_off: "0"
  qos: 1
  retain: true
- platform: mqtt
  name: "sensornode2_relay2"
  state_topic: "home/sensornode2/relay2"
  command_topic: "home/sensornode2/relay2/set/"
  payload_on: "1"
  payload_off: "0"
  qos: 1
  retain: true
- platform: mqtt
  name: "On/Off Sonoff"
  state_topic: "stat/sonoffdual/RESULT"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/sonoffdual/POWER1"
  availability_topic: "tele/sonoffdual/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "On/Off Sonoff2"
  state_topic: "stat/sonoffdual/RESULT"
  value_template: '{{ value_json["POWER2"] }}'
  command_topic: "cmnd/sonoffdual/POWER2"
  availability_topic: "tele/sonoffdual/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: template
  switches:
    wink_siren2:
      value_template: "{{ is_state('wink.siren2', 'on') }}"
      turn_on:
        service: wink.enable_siren
        data:
          entity_id: wink.siren2
          enabled: true
      turn_off:
        service: wink.enable_siren
        data:
          entity_id: wink.siren2
          enabled: false
    wink_siren1:
      value_template: "{{ is_state('wink.siren1', 'on') }}"
      turn_on:
        service: wink.enable_siren
        data:
          entity_id: wink.siren1
          enabled: true
      turn_off:
        service: wink.enable_siren
        data:
          entity_id: wink.siren1
          enabled: false

- platform: mqtt
  name: "PowerPivot1-1"
  state_topic: "stat/powerpivot1/RESULT"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/powerpivot1/POWER1"
  availability_topic: "tele/powerpivot1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true 

- platform: mqtt
  name: "PowerPivot1-2"
  state_topic: "stat/powerpivot1/RESULT"
  value_template: '{{ value_json["POWER2"] }}'
  command_topic: "cmnd/powerpivot1/POWER2"
  availability_topic: "tele/powerpivot1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "PowerPivot2-1"
  state_topic: "stat/powerpivot2/RESULT"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/powerpivot2/POWER1"
  availability_topic: "tele/powerpivot2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true 

- platform: mqtt
  name: "PowerPivot2-2"
  state_topic: "stat/powerpivot2/RESULT"
  value_template: '{{ value_json["POWER2"] }}'
  command_topic: "cmnd/powerpivot2/POWER2"
  availability_topic: "tele/powerpivot2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: "Side Spigot"
  state_topic: "stat/Jinvoo/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/Jinvoo/POWER"
  availability_topic: "tele/Jinvoo/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true 
  
- platform: mqtt
  name: "4chpro 1"
  state_topic: "stat/sonoff4chpro/RESULT"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/sonoff4chpro/POWER1"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "4chpro 2"
  state_topic: "stat/sonoff4chpro/RESULT"
  value_template: '{{ value_json["POWER2"] }}'
  command_topic: "cmnd/sonoff4chpro/POWER2"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "4chpro 3"
  state_topic: "stat/sonoff4chpro/RESULT"
  value_template: '{{ value_json["POWER3"] }}'
  command_topic: "cmnd/sonoff4chpro/POWER3"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "4chpro 4"
  state_topic: "stat/sonoff4chpro/RESULT"
  value_template: '{{ value_json["POWER4"] }}'
  command_topic: "cmnd/sonoff4chpro/POWER4"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  
  
- platform: circadian_lighting
  lights_rgb:
    - light.wink_bed_room
    - light.wink_hallway
    - light.wink_led_strip_bed
    