# - platform: orvibo
  # discovery: false
  # switches:
    # - host: 192.168.47.208
      # name: "Wifi Switch1"

- platform: mqtt
  name: "esp1"
  unique_id: esp1
  state_topic: "home/sonoff/1/1/stat"
  command_topic: "home/sonoff/1/1"
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true
- platform: mqtt
  name: "esp2"
  unique_id: esp2
  state_topic: "home/sonoff/2/1/stat"
  command_topic: "home/sonoff/2/1"
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true
- platform: mqtt
  name: "esp3"
  unique_id: esp3
  state_topic: "stat/esp3/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp3/POWER"
  availability_topic: "tele/esp3/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: true
- platform: mqtt
  name: "esp4"
  unique_id: esp4
  state_topic: "stat/esp4/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp4/POWER"
  availability_topic: "tele/esp4/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: true
- platform: mqtt
  unique_id: esp5
  name: "esp5"
  state_topic: "home/sonoff/5/1/stat"
  command_topic: "home/sonoff/5/1"
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true
- platform: mqtt
  unique_id: esp6
  name: "esp6"
  state_topic: "home/sonoff/6/1/stat"
  command_topic: "home/sonoff/6/1"
  payload_on: "on"
  payload_off: "off"
  qos: 1
  retain: true
- platform: template
  switches:
    wink_siren2:
      value_template: "{{ is_state('wink.siren2', 'on') }}"
      turn_on:
        service: wink.enable_siren
        data:
          entity_id: wink.siren2
          enabled: true
      turn_off:
        service: wink.enable_siren
        data:
          entity_id: wink.siren2
          enabled: false
    wink_siren1:
      value_template: "{{ is_state('wink.siren1', 'on') }}"
      turn_on:
        service: wink.enable_siren
        data:
          entity_id: wink.siren1
          enabled: true
      turn_off:
        service: wink.enable_siren
        data:
          entity_id: wink.siren1
          enabled: false

- platform: mqtt
  name: "PowerPivot2-1"
  state_topic: "stat/powerpivot2/RESULT"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/powerpivot2/POWER1"
  availability_topic: "tele/powerpivot2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true 

- platform: mqtt
  name: "PowerPivot2-2"
  state_topic: "stat/powerpivot2/RESULT"
  value_template: '{{ value_json["POWER2"] }}'
  command_topic: "cmnd/powerpivot2/POWER2"
  availability_topic: "tele/powerpivot2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  
- platform: mqtt
  name: "4chpro 1"
  unique_id: 4chpro-1
  state_topic: "stat/sonoff4chpro/RESULT"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/sonoff4chpro/POWER1"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "4chpro 2"
  unique_id: 4chpro-2
  state_topic: "stat/sonoff4chpro/RESULT"
  value_template: '{{ value_json["POWER2"] }}'
  command_topic: "cmnd/sonoff4chpro/POWER2"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "4chpro 3"
  unique_id: 4chpro-3
  state_topic: "stat/sonoff4chpro/RESULT"
  value_template: '{{ value_json["POWER3"] }}'
  command_topic: "cmnd/sonoff4chpro/POWER3"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  unique_id: 4chpro-4
  name: "4chpro 4"
  state_topic: "stat/sonoff4chpro/RESULT"
  value_template: '{{ value_json["POWER4"] }}'
  command_topic: "cmnd/sonoff4chpro/POWER4"
  availability_topic: "tele/sonoff4chpro/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Bathroom Fan"
  state_topic: "stat/esp_bathroom/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp_bathroom/POWER"
  availability_topic: "tele/esp_bathroom/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  #retain: true 
  optimistic: true

#################################################
#### ROUND
#################################################
- platform: mqtt
  name: "Round 1"
  state_topic: "stat/round/RESULT"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/round/POWER1"
  availability_topic: "tele/round/LWT"
  unique_id: round1
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Round 2"
  unique_id: round2
  state_topic: "stat/round/RESULT"
  value_template: '{{ value_json["POWER2"] }}'
  command_topic: "cmnd/round/POWER2"
  availability_topic: "tele/round/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "Round 3"
  unique_id: round3
  state_topic: "stat/round/RESULT"
  value_template: '{{ value_json["POWER3"] }}'
  command_topic: "cmnd/round/POWER3"
  availability_topic: "tele/round/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "esp7"
  unique_id: esp7
  state_topic: "stat/esp7/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp7/POWER"
  availability_topic: "tele/esp7/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  json_attributes_topic: "tele/esp7/SENSOR"
  json_attributes_template: "{{ value_json['ENERGY'] | tojson }}"
- platform: mqtt
  name: "esp8"
  unique_id: esp8
  state_topic: "stat/esp8/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp8/POWER"
  availability_topic: "tele/esp8/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "esp9"
  unique_id: esp9
  state_topic: "stat/esp9/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp9/POWER"
  availability_topic: "tele/esp9/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: "esp11"
  unique_id: esp11
  state_topic: "stat/esp11/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp11/POWER"
  availability_topic: "tele/esp11/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  json_attributes_topic: "tele/esp11/SENSOR"
  json_attributes_template: "{{ value_json['ENERGY'] | tojson }}"
- platform: mqtt
  name: "esp12"
  unique_id: esp12
  state_topic: "stat/esp12/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp12/POWER"
  availability_topic: "tele/esp12/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  json_attributes_topic: "tele/esp12/SENSOR"
  json_attributes_template: "{{ value_json['ENERGY'] | tojson }}"
- platform: mqtt
  name: "esp13"
  unique_id: esp13
  state_topic: "stat/esp13/RESULT"
  value_template: '{{ value_json["POWER"] }}'
  command_topic: "cmnd/esp13/POWER"
  availability_topic: "tele/esp13/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  json_attributes_topic: "tele/esp13/SENSOR"
  json_attributes_template: "{{ value_json['ENERGY'] | tojson }}"

