esphome:
  name: ahr-085-2

esp8266:
  board: esp01_1m

substitutions:
  devicename: ahr-085-2
  upper_devicename: ahr-085-2
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

api:
  encryption:
    key: "rCskpOQEJhIdAsqXer+uIj66WcTXlxWLBwbcnmxEszw="
    
switch:
  - platform: gpio
    name: "ahr-085-2-Relay1"
    id: relay1
    pin:
      number: GPIO14
  - platform: gpio
    name: "ahr-085-2-Relay2"
    id: relay2
    pin:
      number: GPIO12
  - platform: gpio
    name: "ahr-085-2-Relay3"
    pin:
      number: GPIO13
    id: relay3
      
light:
# Blue LED PWM
# GPIO4
  - platform: monochromatic
    name: "ahr-085-2-PowerStrip-Blue_LED"
    output: output_component_blue

output:
#Blue LED
  - platform: esp8266_pwm
    id: output_component_blue
    pin: GPIO5
    inverted: yes

# Button & Automation to toggle all switches
# GPIO5

binary_sensor:
  - platform: gpio
    pin: GPIO4
    id: button
    name: "PowerStrip_Button"
    on_press:
      - switch.toggle: relay1
      - switch.toggle: relay2
      - switch.toggle: relay3
    internal: True
