esphome:
  name: ahr-085-3

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "93ow/yHLEHUCqBTbH4HZB4lJffPjwFKytTwnHsivSlI="

ota:
  password: "c9363fc9c4b74f91aeabe0ca08e74f23"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ahr-085-3 Fallback Hotspot"
    password: "mxdrpwTkmBsb"

captive_portal:

web_server:
  port: 80
    
switch:
  - platform: gpio
    name: "ahr-085-3-Relay1"
    id: relay1
    pin:
      number: GPIO14
  - platform: gpio
    name: "ahr-085-3-Relay2"
    id: relay2
    pin:
      number: GPIO12
  - platform: gpio
    name: "ahr-085-3-Relay3"
    pin:
      number: GPIO13
    id: relay3
      
light:
# Blue LED PWM
# GPIO4
  - platform: monochromatic
    name: "ahr-085-3-PowerStrip-Blue_LED"
    output: output_component_blue

output:
#Blue LED
  - platform: esp8266_pwm
    id: output_component_blue
    pin: GPIO5
    inverted: yes

# Button & Automation to toggle all switches
# GPIO5

binary_sensor:
  - platform: gpio
    pin: GPIO4
    id: button
    name: "PowerStrip_Button"
    on_press:
      - switch.toggle: relay1
      - switch.toggle: relay2
      - switch.toggle: relay3
    internal: True


substitutions:
  devicename: ahr-085-3
  upper_devicename: ahr-085-3
packages:
  device_base: !include default-sensors-switches.yaml