esphome:
  name: alliance-temp
  friendly_name: alliance-temp
substitutions:
  devicename: alliance-temp
  upper_devicename: Alliance-temp
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ATtXPeimYkxrF+xeGgR811e0ueix+5TduhyBtpsZABs="

mqtt:
  broker: 192.168.47.103
  username: alliance-temp
  password: alliance-temp
  discovery: true

wifi:
  networks:
    - ssid: !secret wifi_ssid_dog_iot
      password: !secret wifi_password_dog_iot
      priority: 4
    - ssid: !secret wifi_ssid_dog
      password: !secret wifi_password_dog
      priority: 2
    - ssid: !secret wifi_ssid_chandler2
      password: !secret wifi_password_chandler2


captive_portal:

web_server:
  
sensor:
  - platform: dht
    model: DHT22
    pin: D3
    temperature:
      name: "Temperature"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Humidity"
    update_interval: 60s

    