esphome:
  name: basement-v2

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
#  level: debug

# Enable Home Assistant API
api:
  encryption:
    key: "sebyNmztsE5MDkRfg5iKtlkRh0hA5qLzSRkBIKUKM9s="

ota:
  password: "b9d14abcfc8aad083c4b7ea18f35323c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Basement-V2 Fallback Hotspot"
    password: "9KM2wjrESpbN"

captive_portal:

web_server:
  port: 80

switch:
  - platform: gpio
    name: Relay 1
    pin: GPIO32
    id: relay
  - platform: restart
    name: ESP Basement v2 Restart

binary_sensor:
  - platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    filters:
      - delayed_on: 10ms
    on_press:
      - switch.toggle: relay
  - platform: status
    name: ESP Basement V2 Status
  - platform: gpio
    pin:
      number: D18
      mode: INPUT_PULLUP
    name: “Front Door”
    device_class: door
    filters:
      - delayed_on: 1000ms
#      - delayed_off: 1000ms
  - platform: gpio
    pin: 
       number: D19
       mode: INPUT_PULLUP
    name: “Basement Door”
    device_class: door
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

dallas:
   pin: GPIO5
   update_interval: 30s
  
sensor:
  - platform: dallas
    address: 0x1627f6271e64ff28
    name: "Stove Air Sensor"
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"
    device_class: "temperature"
    state_class: "measurement"
  - platform: wifi_signal
    name: Basement V2 WiFi Signal
    update_interval: 60s

  