substitutions:
  devicename: basement-node
  upper_devicename: Basement-Node

esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2
  
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    name: “Front Door”
    device_class: door
    filters:
      - delayed_on: 2000ms
#      - delayed_off: 1000ms
  - platform: gpio
    pin: 
       number: D6
       mode: INPUT_PULLUP
    name: “Basement Door”
    device_class: door
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    
