esphome:
  name: basement-v2

esp32:
  board: esp32dev
  framework:
    type: arduino

substitutions:
  devicename: basement-v2
  upper_devicename: basement-v2
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

api:
  encryption:
    key: "sebyNmztsE5MDkRfg5iKtlkRh0hA5qLzSRkBIKUKM9s="

switch:
  - platform: gpio
    name: Fire Blower
    pin: GPIO32
    id: relay

binary_sensor:
  - platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    filters:
      - delayed_on: 10ms
    on_press:
      - switch.toggle: relay
  - platform: gpio
    pin:
      number: 18
      mode: INPUT_PULLUP
    name: “Front Door”
    device_class: door
    filters:
      - delayed_on: 1000ms
#      - delayed_off: 1000ms
  - platform: gpio
    pin: 
       number: 19
       mode: INPUT_PULLUP
    name: “Basement Door”
    device_class: door
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

one_wire:
   platform: gpio
   pin: GPIO5
  
sensor:
  - platform: dallas_temp
    address: 0x1627f6271e64ff28
    name: "Stove Air Sensor"
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"
    device_class: "temperature"
    state_class: "measurement"

status_led:
  pin: GPIO2
  