substitutions:
  devicename: chicken-sensor
  upper_devicename: Chicken-Sensor

esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2

packages:
  device_base: !include common.yaml

#cover:
#  - platform: template
#    name: Chicken Door
#    lambda: |-
#      if (id(door_status).state) {
#        return COVER_OPEN;
#      } else {
#        return COVER_CLOSED;
#      }
#    open_action:
#      - switch.turn_on: door
#    close_action:
#      - switch.turn_on: door
#    stop_action:
#      - switch.turn_off: door

switch:
  - platform: gpio
    pin:
      number: D1
      inverted: true
    name: Chicken Door Switch
    id: door
    on_turn_on:
    - switch.toggle: coop_door_status
    - delay: 15000ms
    - switch.turn_off: door
  - platform: gpio
    pin:
      number: D5
      inverted: true
    name: Chicken Pen Switch
    id: pen
    on_turn_on:
    - switch.toggle: pen_door_status
    - delay: 15000ms
    - switch.turn_off: pen
  - platform: template
    name: Chicken Pen Door Status
    id: pen_door_status
    restore_state: true
    optimistic: true
  - platform: template
    name: Chicken Door Status
    id: coop_door_status
    optimistic: true
    restore_state: true

binary_sensor:
  - platform: gpio
    id: door_status
    pin:
      number: D6
    #  mode: INPUT_PULLUP
    name: Chicken Door
    device_class: door
    filters:
      - delayed_on: 1000ms
      - delayed_off: 1000ms
  - platform: gpio
    id: pen_status
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: true
    name: Chicken Door Button
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: true
    name: Chicken Pen Button

sensor:
  - platform: dht
    pin: D4
    model: AM2302
    temperature:
      name: "Chicken Coop Temperature"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Chicken Coop Humidity"
    update_interval: 60s

