esphome:
  name: chicken-sensor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "68e6859753bdbf4cb3c04bf5cc311846"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Chicken-Sensor Fallback Hotspot"
    password: "tRJEeOOclmr9"

captive_portal:

cover:
  - platform: template
    name: "Chicken Door"
    lambda: |-
      if (id(door_status).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: door
    close_action:
      - switch.turn_on: door
    stop_action:
      - switch.turn_off: door


switch:
  - platform: gpio
    pin:
      number: D1
      inverted: true
    name: "Chicken Door Switch"
    id: door
    on_turn_on:
    - delay: 15000ms
    - switch.turn_off: door
  - platform: gpio
    pin:
      number: D5
      inverted: true
    name: "Chicken Pen Switch"
    id: pen
    on_turn_on:
    - delay: 15000ms
    - switch.turn_off: pen
    - switch.toggle: pen_door_status
  - platform: restart
    name: "ESP Chicken Restart"
  - platform: template
    name: "Chicken Pen Door Status"
    id: pen_door_status
    optimistic: true


binary_sensor:
  - platform: gpio
    id: door_status
    pin:
      number: D6
      mode: INPUT_PULLUP
    name: “Chicken Door”
    device_class: door
    filters:
      - delayed_on: 1000ms
      - delayed_off: 1000ms
  - platform: gpio
    id: pen_status
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: true
    name: “Chicken Door Button”
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: true
    name: “Chicken Pen Button”
  - platform: status
    name: "Chicken Sensor"


sensor:
  - platform: dht
    pin: D4
    temperature:
      name: "Chicken Coop Temperature"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Chicken Coop Humidity"
    update_interval: 60s
    
web_server:
  port: 80
    
