wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${devicename} Fallback
    password: !secret wifi_pass

captive_portal:


web_server:
  port: 80
    
switch:
  - platform: restart
    name: ESP ${upper_devicename} Restart

binary_sensor:
  - platform: status
    name: ESP ${upper_devicename} Status
    
sensor:
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
    update_interval: 60s

#substitutions:
#  devicename: livingroom
#  upper_devicename: Livingroom
#packages:
  #device_base: !include common-2.yaml
