#substitutions:
#  devicename: 
#  upper_devicename: 
#packages:
#  device_base: !include common.yaml
#  device_switches_sensors: !include default-sensors-switches.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${devicename} Fallback
    password: !secret wifi_pass

captive_portal:

ota:
  password: !secret esp_ota_pw
  id: ota_id

web_server:
  port: 80

