#substitutions:
#  devicename: livingroom
#  upper_devicename: Livingroom

# Enable logging
logger:

# Enable Home Assistant API
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${devicename} Fallback
    password: !secret wifi_pass

captive_portal:

ota:
  password: !secret esp_ota_pw


web_server:
  port: 80

#packages:
  #device_base: !include common.yaml
