#substitutions:
#  devicename: livingroom
#  upper_devicename: Livingroom

# Enable logging
logger:

# Enable Home Assistant API
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${upper_devicename} Fallback Hotspot
    password: !secret wifi_pass

captive_portal:

ota:
  password: !secret esp_ota_pw


web_server:
  port: 80
    
switch:
  - platform: restart
    name: ESP ${upper_devicename} Restart

binary_sensor:
  - platform: status
    name: ESP ${upper_devicename} Status


#packages:
  #device_base: !include common.yaml
