#packages:
  #device_switches_sensors: !include default-sensors-switches.yaml

switch:
  - platform: restart
    name: ESP ${upper_devicename} Restart

binary_sensor:
  - platform: status
    name: ESP ${upper_devicename} Status
    
sensor:
  - platform: wifi_signal
    name: ESP ${upper_devicename} WiFi Signal
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "ESP ${upper_devicename} IP Address"