esphome:
  name: esp-round

esp8266:
  board: esp01_1m
  
substitutions:
  devicename: esp-round
  upper_devicename: ESP-Round
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

api:
  encryption:
    key: "EQCzKWuJmFqXAGOMHLvWJe/eei3Dl27PlIrdwtChKKA="

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
    name: "Button 1"
    id: button1
    internal: True
    on_press:
      - switch.toggle: relay1
      - switch.toggle: relay1
      - switch.toggle: relay3

switch:
  - platform: gpio
    pin: GPIO14
    id: relay1
    name: Outlet 1
  - platform: gpio
    pin: GPIO05
    id: relay2
    name: Outlet 2
  - platform: gpio
    pin: GPIO4
    id: relay3
    name: Outlet 3
