esphome:
  name: esp-printer-strip

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "cL7VkAgoLfOPk9QA14vJKE+czzqMNoCqiEph3eKc0MI="

ota:
  password: "40368de8b77000b6214d2338376b98b8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Printer-Strip"
    password: "wLBw9r0InmkO"

captive_portal:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
    name: "Button 1"
    id: button1
    internal: True
    on_press:
      - switch.toggle: relay2

switch:
  - platform: gpio
    pin: GPIO14
    id: relay1
    name: 3D Printer
  - platform: gpio
    pin: GPIO04
    id: relay2
    name: HP Printer
  - platform: gpio
    pin: GPIO12
    id: relay3
    name: Switch 3
  - platform: gpio
    pin: GPIO05
    id: relay4
    name: Switch 4
  - platform: gpio
    pin: GPIO13
    id: relay5
    name: USB Outlets
