esphome:
  name: esp-round

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EQCzKWuJmFqXAGOMHLvWJe/eei3Dl27PlIrdwtChKKA="

ota:
  password: "ae2724675dea59ade790ec8a19a8f2d1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Round Fallback Hotspot"
    password: !secret wifi_password
    
captive_portal:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
    name: "Button 1"
    id: button1
    internal: True
    on_press:
      - switch.toggle: relay1
      - switch.toggle: relay1
      - switch.toggle: relay3

switch:
  - platform: gpio
    pin: GPIO14
    id: relay1
    name: Outlet 1
  - platform: gpio
    pin: GPIO05
    id: relay2
    name: Outlet 2
  - platform: gpio
    pin: GPIO4
    id: relay3
    name: Outlet 3

substitutions:
  devicename: esp-round
  upper_devicename: ESP-Round
packages:
  device_base: !include default-sensors-switches.yaml