esphome:
  name: esp-printer-strip

esp8266:
  board: esp01_1m

substitutions:
  devicename: printer-strip
  upper_devicename: printer-strip
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

api:
  encryption:
    key: "cL7VkAgoLfOPk9QA14vJKE+czzqMNoCqiEph3eKc0MI="

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
    name: "Button 1"
    id: button1
    internal: True
    on_press:
      - switch.toggle: relay2

light:
# Blue LED PWM
# GPIO4
  - platform: monochromatic
    name: "PowerStrip-Blue_LED"
    output: output_component_blue

output:
#Blue LED
  - platform: esp8266_pwm
    id: output_component_blue
    pin: GPIO0
    inverted: yes

switch:
  - platform: gpio
    pin: GPIO14
    id: relay1
    name: 3D Printer
  - platform: gpio
    pin: GPIO04
    id: relay2
    name: HP Printer
  - platform: gpio
    pin: GPIO12
    id: relay3
    name: Switch 3
  - platform: gpio
    pin: GPIO05
    id: relay4
    name: Switch 4
  - platform: gpio
    pin: GPIO13
    id: relay5
    name: USB Outlets

