substitutions:
  devicename: winnebago-plug
  upper_devicename: Winnebago-Plug

esphome:
  name: ${devicename}
  comment: winnebago plug

esp8266:
  board: esp01_1m

packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

wifi:
  networks:
    - ssid: !secret wifi_ssid_dog_iot
      password: !secret wifi_password_dog_iot
      priority: 4
    - ssid: !secret wifi_ssid_dog
      password: !secret wifi_password_dog
      priority: 2

api:
  reboot_timeout: 0s

mqtt:
  broker: 192.168.47.103
  username: winnebago-plug
  password: winnebago-plug
  discovery: true
  discovery_unique_id_generator: mac

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${devicename} Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${devicename} Status"

sensor:
  - platform: cse7766
    current:
      name: Current
      accuracy_decimals: 1
      filters:
        - throttle_average: ${update_interval}
    voltage:
      name: Voltage
      accuracy_decimals: 1
      filters:
        - throttle_average: ${update_interval}
    power:
      name: Power
      id: wattage
      accuracy_decimals: 1
      filters:
        - throttle_average: ${update_interval}
  - platform: total_daily_energy
    name: Total Daily Energy
    id: tde
    power_id: wattage
    filters:
        - multiply: 0.001  ## convert Wh to kWh
    unit_of_measurement: kWh
    state_class: total_increasing

time:
  - platform: homeassistant
    id: homeassistant_time

switch:
  - platform: gpio
    name: "${devicename}"
    pin: GPIO12
    id: relay

status_led:
  pin: GPIO13


