substitutions:
  devicename: esp11
  upper_devicename: esp11

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

packages:
  device_base: !include common.yaml

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${devicename} Button
    on_press:
      - switch.toggle: relay
  - platform: status
    name: ${devicename} Status

sensor:
  - platform: cse7766
    current:
      name: ${devicename} Current
      accuracy_decimals: 1
    voltage:
      name: ${devicename} Voltage
      accuracy_decimals: 1
    power:
      name: ${devicename} Power
      accuracy_decimals: 1
switch:
  - platform: gpio
    name: ${devicename}
    pin: GPIO12
    id: relay

#ota:
 # password: "e941c8e8e979af02d9630b7fd0335ede"
#  password: "fcb3e800936fb0d6a8dfc93455e0b458"

    