esphome:
  name: esp2

esp8266:
  board: esp01_1m

substitutions:
  devicename: esp2
  upper_devicename: esp2
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

api:
  encryption:
    key: "+wrVmsIkCghtgB/A/EfUHzUXMX6i9rXQ84rNhLUHyTw="

switch:
  - platform: gpio
    pin: GPIO12
    name: "Driveway Outlets"
    id: fan_relay

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: True
    id: bathroom_fan_relay_button
    on_press:
      then:
        - switch.toggle: fan_relay