esphome:
  name: esp32-bluetooth

substitutions:
  device_name: sense-u
  friendly_name: ESP32-bluetooth

esp32:
  board: esp32dev
  framework:
    type: arduino


# Enable Home Assistant API
api:
  encryption:
    key: "gsAx1prducgcRxA/0CoAZReQLnQgqf9Ta4e2Qlcn79g="

ota:
  password: "e569482973c9b18d0eb778e2db76a98b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Bluetooth Fallback Hotspot"
    password: "1QZJ21nZK82m"

captive_portal:
    
logger:
#  level: VERY_VERBOSE

esp32_ble_tracker:


external_components:
  - source: github://andyboeh/esphome-sense-u
    components: senseu

ble_client:
  - mac_address: e7:ca:2d:0b:0b:0f
    id: my_senseu_ble
  - mac_address: F1:1F:35:49:ED:7E
    id: pink_toy
  - mac_address: E6:14:52:EB:3A:24
    id: blue_toy

senseu:
  - ble_client_id: my_senseu_ble
    id: my_senseu
    # baby_code is optional. Needs to be retrieved during pairing phase.
    # This allows using the Sense-U with multiple devices, e.g. at different
    # locations.
    
    # baby_code: aabbccddeeff

# Example configuration entry
sensor:
  - platform: senseu
    id: my_senseu
    breath_rate: 
      name: Breath Rate
    temperature: 
      name: Temperature
    humidity: 
      name: Humidity
    battery_level:
      name: Battery Level
  # Uptime sensor
  - platform: uptime
    name: ${friendly_name} Uptime
  # WiFi Signal sensor
  - platform: wifi_signal
    name: ${friendly_name} Wifi Signal
    update_interval: 60s
    
# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
  - platform: senseu
    id: my_senseu
    posture:
      name: Posture
    status:
      name: State
  - platform: homeassistant
    name: "Toy Pink Speed"
    entity_id: input_select.toy_pink_status
    id: toy_pink_speed
    on_value:
          then:
            - ble_client.ble_write:
                id: pink_toy
                service_uuid: 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
                characteristic_uuid: 6E400002-B5A3-F393-E0A9-E50E24DCCA9E
                value: !lambda |-
                  if ( x == "high") {
                  return {0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x65, 0x3a, 0x32, 0x30, 0x3b};
                  }
                  if ( x == "med") {
                  return {0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x65, 0x3a, 0x31, 0x30, 0x3b};
                  }
                  if ( x == "low") {
                  return {0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x65, 0x3a, 0x30, 0x31, 0x3b};
                  }
                  if ( x == "off") {
                  return {0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x65, 0x3a, 0x30, 0x3b};
                  } else {
                  return {0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x65, 0x3a, 0x30, 0x3b};
                  }
  - platform: homeassistant
    name: "Toy Blue Speed"
    entity_id: input_select.toy_blue_status
    id: toy_blue_speed
    on_value:
          then:
            - ble_client.ble_write:
                id: blue_toy
                service_uuid: 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
                characteristic_uuid: 6E400002-B5A3-F393-E0A9-E50E24DCCA9E
                value: !lambda |-
                  if ( x == "high") {
                  return {0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x65, 0x3a, 0x32, 0x30, 0x3b};
                  }
                  if ( x == "med") {
                  return {0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x65, 0x3a, 0x31, 0x30, 0x3b};
                  }
                  if ( x == "low") {
                  return {0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x65, 0x3a, 0x30, 0x31, 0x3b};
                  }
                  if ( x == "off") {
                  return {0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x65, 0x3a, 0x30, 0x3b};
                  } else {
                  return {0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x65, 0x3a, 0x30, 0x3b};
                  }

binary_sensor:
  - platform: senseu
    id: my_senseu
    breath:
      name: Breath Alarm
    posture:
      name: Posture Alarm
    temperature:
      name: Temperature Alarm
    battery:
      name: Battery Alarm

switch:
  - platform: senseu
    senseu_id: my_senseu
    name: Power Switch
  - platform: ble_client
    ble_client_id: pink_toy
    name: "Enable pink toy"
  - platform: ble_client
    ble_client_id: blue_toy
    name: "Enable blue toy"
  - platform: template
    name: "Pink Toy"
    optimistic: True
    turn_on_action:
      - ble_client.ble_write:
          id: pink_toy
          service_uuid: 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
          characteristic_uuid: 6E400002-B5A3-F393-E0A9-E50E24DCCA9E
          # List of bytes to write.
          value: [0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x65, 0x3a, 0x30, 0x31, 0x3b]
    turn_off_action:
      - ble_client.ble_write:
          id: pink_toy
          service_uuid: 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
          characteristic_uuid: 6E400002-B5A3-F393-E0A9-E50E24DCCA9E
          # List of bytes to write.
          value: [0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x65, 0x3a, 0x30, 0x3b]
  - platform: template
    name: "Blue Toy"
    optimistic: True
    turn_on_action:
      - ble_client.ble_write:
          id: blue_toy
          service_uuid: 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
          characteristic_uuid: 6E400002-B5A3-F393-E0A9-E50E24DCCA9E
          # List of bytes to write.
          value: [0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x65, 0x3a, 0x30, 0x31, 0x3b]
    turn_off_action:
      - ble_client.ble_write:
          id: blue_toy
          service_uuid: 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
          characteristic_uuid: 6E400002-B5A3-F393-E0A9-E50E24DCCA9E
          # List of bytes to write.
          value: [0x56, 0x69, 0x62, 0x72, 0x61, 0x74, 0x65, 0x3a, 0x30, 0x3b]

