substitutions:
  devicename: esp5
  upper_devicename: esp5

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  comment: Garage Fire Stick

packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${devicename} Button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: ${devicename}
    pin: GPIO12
    id: relay

status_led:
  pin: GPIO13