substitutions:
  devicename: esp9
  upper_devicename: esp9

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  comment: garage attic fan

packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${devicename} Button
    on_press:
      - switch.toggle: relay

sensor:
  - platform: cse7766
    current:
      name: ${devicename} Current
      accuracy_decimals: 1
      filters:
        - throttle_average: ${update_interval}
    voltage:
      name: ${devicename} Voltage
      accuracy_decimals: 1
      filters:
        - throttle_average: ${update_interval}
    power:
      name: ${devicename} Power
      accuracy_decimals: 1
      filters:
        - throttle_average: ${update_interval}
switch:
  - platform: gpio
    name: ${devicename}
    pin: GPIO12
    id: relay

status_led:
  pin: GPIO13