substitutions:
  devicename: garage-lights
  upper_devicename: Garage-Lights

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

logger:
  baud_rate: 0

uart:
  tx_pin: GPIO01
  rx_pin: GPIO03
  baud_rate: 19200

switch:
  - platform: template
    id: relay_1
    turn_on_action:
      if:
        condition:
          switch.is_off: relay_2
        then:
          - uart.write: [0xA0, 0x04, 0x01, 0xA1]
        else:
          - uart.write: [0xA0, 0x04, 0x03, 0xA1]
    turn_off_action:
      if:
        condition:
          switch.is_off: relay_2
        then:
          - uart.write: [0xA0, 0x04, 0x00, 0xA1]
        else:
          - uart.write: [0xA0, 0x04, 0x02, 0xA1]
    optimistic: true

  - platform: template
    id: relay_2
    turn_on_action:
      if:
        condition:
          switch.is_off: relay_1
        then:
          - uart.write: [0xA0, 0x04, 0x02, 0xA1]
        else:
          - uart.write: [0xA0, 0x04, 0x03, 0xA1]
    turn_off_action:
      if:
        condition:
          switch.is_off: relay_1
        then:
          - uart.write: [0xA0, 0x04, 0x00, 0xA1]
        else:
          - uart.write: [0xA0, 0x04, 0x01, 0xA1]
    optimistic: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - light.toggle: light_1

  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_2
    on_press:
      then:
        - light.toggle: light_2


status_led:
  pin:
    number: GPIO13
    inverted: yes

output:
  - platform: template
    type: binary
    id: out_1
    write_action:
      if:
        condition:
          light.is_on: light_1
        then:
          - switch.turn_on: relay_1
        else:
          - switch.turn_off: relay_1

  - platform: template
    type: binary
    id: out_2
    write_action:
      if:
        condition:
          light.is_on: light_2
        then:
          - switch.turn_on: relay_2
        else:
          - switch.turn_off: relay_2

light:
  - platform: binary
    name: "Garage Lights Front"
    id: light_2
    output: out_2

  - platform: binary
    name: "Garage Lights Rear"
    id: light_1
    output: out_1
