substitutions:
  devicename: garage-door
  upper_devicename: Garage-Door

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini

packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    name: “Garage Entry”
    device_class: door
    filters:
      - invert:
