substitutions:
  devicename: garage-door
  upper_devicename: Garage-Door

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    name: “Garage Entry”
    device_class: door
    filters:
      - invert:
   
<<: !include common.yaml