substitutions:
  devicename: garage-door-lights
  upper_devicename: Garage-Door-Lights

esphome:
  name: garage-door-lights
  friendly_name: garage-door-lights

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "2wdqAMPaTvnQIR7G77G7XshpxVwTs7PonOr9jX8Gr4w="

ota:
  - platform: esphome

captive_portal:

packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: true
    name: "Garage Door"
    device_class: door
    filters:
      - delayed_on_off: 100ms

  - platform: gpio
    pin:
      number: GPIO25
      mode: INPUT_PULLUP
      inverted: true
    name: "Switch 1"
    filters:
      - delayed_on_off: 50ms
    on_state:
      - switch.toggle: relay_1
  - platform: gpio
    pin:
      number: GPIO26
      mode: INPUT_PULLUP
      inverted: true
    name: "Switch 2"
    filters:
      - delayed_on_off: 50ms
    on_state:
      - switch.toggle: relay_2
    
web_server:
  
switch:
  - platform: gpio
    pin: GPIO16
    name: "Relay 1"
    id: relay_1

  - platform: gpio
    pin: GPIO17
    name: "Relay 2"
    id: relay_2

status_led:
  pin:
    number: GPIO23
    inverted: yes

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true