substitutions:
  devicename: garage-door-lights
  upper_devicename: Garage-Door-Lights

esphome:
  name: garage-door-lights
  friendly_name: garage-door-lights

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: "2wdqAMPaTvnQIR7G77G7XshpxVwTs7PonOr9jX8Gr4w="

ota:
  - platform: esphome

captive_portal:

packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO32
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Garage Door"
    device_class: door
    
web_server:
  
switch:
  - platform: gpio
    pin: GPIO16
    name: "Relay 1"
    id: relay_1

  - platform: gpio
    pin: GPIO17
    name: "Relay 2"
    id: relay_2

light:
  - platform: binary
    name: "Status LED"
    output: led3_output

output:
  - platform: gpio
    pin: GPIO23
    id: led3_output

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true