substitutions:
  devicename: midea-ac-craft
  upper_devicename: Craft Room

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini

# Disable logging over UART (required)
logger:
  baud_rate: 0

# UART settings for Midea dongle (required)
uart:
  tx_pin: 3
  rx_pin: 1
  baud_rate: 9600

# Main settings
climate:
  - platform: midea
    name: "Craft Room"
    visual:
      min_temperature: 60 °F
      max_temperature: 80 °F

<<: !include common.yaml