esphome:
  name: midea-ac-bed
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Midea-Ac-Bed Fallback Hotspot"
    password: !secret wifi_pass

captive_portal:

# Enable Home Assistant API
api:

ota:

# Disable logging over UART (required)
logger:
  baud_rate: 0

# UART settings for Midea dongle (required)
uart:
  tx_pin: 3
  rx_pin: 1
  baud_rate: 9600

# Optional (if you want modify settings)
#midea_dongle:


# Main settings
climate:
  - platform: midea
    name: "Bed Room"
    visual:
      min_temperature: 60 °F
      max_temperature: 80 °F

switch:
  - platform: restart
    name: "ESP Midea AC Restart"
