substitutions:
  devicename: midea-ac-craft
  upper_devicename: Craft Room MiniSplit

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp12e
  
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

# Disable logging over UART (required)
logger:
  baud_rate: 0

# UART settings for Midea dongle (required)
uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

# Main settings
climate:
  - platform: midea
    name: "Craft Room"
    id: craft
    visual:
      min_temperature: 60 °F
      max_temperature: 80 °F


sensor:
 # - platform: uptime
 #   name: Craft Room MiniSplit Uptime Sensor
  - platform: template
    name: "Craft Minisplit Temp"
    lambda: return(id(craft).current_temperature);
    unit_of_measurement: "°C"
    icon: "mdi:temperature-fahrenheit"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    update_interval: 60s