substitutions:
  devicename: midea-ac-office
  upper_devicename: Office MiniSplit

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp12e
  
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

# Disable logging over UART (required)
logger:
  baud_rate: 0

# UART settings for Midea dongle (required)
uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

# Main settings
climate:
  - platform: midea
    id: climate_me
    name: "Office"
    visual:
      min_temperature: 60 °F
      max_temperature: 80 °F

sensor:
#  - platform: uptime
#    name: Bedroom Minisplit Uptime Sensor
  - platform: template
    name: "Office Minisplit Temp"
    lambda: return(id(climate_me).current_temperature);
    unit_of_measurement: "°C"
    icon: "mdi:temperature-fahrenheit"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    update_interval: 60s
