esphome:
  name: minimal
  friendly_name: minimal

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "bnv4ZTtEXLJh0eHORAuC+CkQ5q/kWEY4svbmux3GzB8="

ota:
- platform: esphome
  password: !secret esp_ota_pw
  id: ota_id

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.50.48

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Minimal Fallback Hotspot"
    password: "CFRcv8LOV1fX"

captive_portal:
    