substitutions:
  id_prefix: ratsecondbay
  friendly_name: "Second Bay"
  devicename: rat-secondbay
  upper_devicename: "Second Bay"
  uart_tx_pin: D1
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml 
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base_secplusv1.yaml]
    refresh: 1s

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  project:
    name: ratgdo.esphome
    version: "2.5i"

ota:
  - id: !remove ratgdo_ota

esp8266:
  board: d1_mini
  restore_from_flash: true

dashboard_import:
  package_import_url: github://ratgdo/esphome-ratgdo/v25iboard_secplusv1.yaml@main

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

api:
  id: api_server

#improv_serial:

# Logger must be at least debug (default)
logger:
#  level: debug
  
# # Example configuration entry
# debug:
#   update_interval: 5s

# text_sensor:
#   - platform: debug
#     device:
#       name: "Device Info"
#     reset_reason:
#       name: "Reset Reason"

# sensor:
#   - platform: debug
#     free:
#       name: "Heap Free"
#     fragmentation:
#       name: "Heap Fragmentation"
#     block:
#       name: "Heap Max Block"
#     loop_time:
#       name: "Loop Time"
#   - platform: uptime
#     type: seconds
#     name: ${friendly_name} Uptime Sensor

