substitutions:
  id_prefix: ratsecondbay
  friendly_name: "Second Bay"
  devicename: rat-secondbay
  upper_devicename: "Second Bay"
  uart_tx_pin: GPIO21
  uart_rx_pin: GPIO20
  input_obst_pin: GPIO5
  status_door_pin: GPIO1
  status_obstruction_pin: GPIO10
  dry_contact_open_pin: GPIO3
  dry_contact_close_pin: GPIO4
  dry_contact_light_pin: GPIO9

packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml 
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base_secplusv1.yaml]
    refresh: 1s

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  project:
    name: ratgdo.esphome
    version: "2.5i"

web_server_base:
  
ota:
  - platform: esphome
    id: !remove ${id_prefix}_ratgdo_ota
  - platform: web_server
    id: !remove ${id_prefix}_ratgdo_ota_ws

esp32:
  variant: esp32c3
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://ratgdo/esphome-ratgdo/v25iboard_secplusv1.yaml@main

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

api:
  id: api_server

captive_portal: 

logger:
  level: DEBUG
  hardware_uart: UART0
  baud_rate: 115200

wifi:
  ap:
    ssid: testing Fallback Hotspot
    password: password
  
  

