esphome:
  name: ${unique_id}
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

substitutions:
  devicename: yagala_sm-so301_01
  upper_devicename: sm-so301_01
  displayname: "Desk Power Strip"
  unique_id: "yagala_sm-so301_01"
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

switch:
  - platform: gpio
    name: "${displayname} USB Power"
    id: usb_power
    pin:
      number: GPIO16
  - platform: gpio
    name: "${displayname} 1"
    id: relay1
    inverted: true
    pin:
      number: GPIO4
  - platform: gpio
    name: "${displayname} 2"
    inverted: true
    pin:
      number: GPIO13
    id: relay2
  - platform: gpio
    name: "${displayname} 3"
    inverted: true
    id: relay3
    pin:
      number: GPIO12
  - platform: gpio
    name: "${displayname} 4"
    inverted: true
    id: relay4
    pin:
      number: GPIO14

light:
  # Blue LED PWM
  # GPIO0
  - platform: monochromatic
    name: "${displayname} Blue LED"
    output: output_component_blue

output:
  #Blue LED
  - platform: esp8266_pwm
    id: output_component_blue
    pin: GPIO0
    inverted: true

binary_sensor:
  # Button & Automation to toggle all switches
  # GPIO5
  - platform: gpio
    pin: GPIO5
    id: button
    name: "${displayname} Button"
    on_press:
      - switch.toggle: relay1
      - switch.toggle: relay2
      - switch.toggle: relay3
      - switch.toggle: relay4
      - switch.toggle: usb_power
    internal: True
