esphome:
  name: sonoff-b-1

esp8266:
  board: esp01_1m

substitutions:
  devicename: sonoff-b-1
  upper_devicename: sonoff-b-1
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

# Enable Home Assistant API
api:
  encryption:
    key: "Co5PNA8LChs1HCIFb+9sVTdvoIuQdD6OH6jWgjvXjo4="

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes