esphome:
  name: ${devicename}
  comment: air hose solenoid
        
esp8266:
  board: esp01_1m

substitutions:
  devicename: sonoff-b-2
  upper_devicename: sonoff-b-2
  
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${upper_devicename} Button"
    on_press:
      - switch.turn_on: relay
    on_release:
      - switch.turn_off: relay

switch:
  - platform: gpio
    name: "${upper_devicename} Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
