esphome:
  name: ${devicename}

esp8266:
  board: esp01_1m

substitutions:
  devicename: sonoff-b-3
  upper_devicename: sonoff-b-3
  
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${upper_devicename} Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${upper_devicename} Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes