substitutions:
  devicename: stove-sensor
  upper_devicename: Stove-Sensor

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini
  
packages:
  device_base: !include common.yaml
  device_switches_sensors: !include default-sensors-switches.yaml

one_wire:
   platform: gpio
   pin: D4
  
sensor:
  - platform: dallas_temp
    address: 0xF50517A19A43FF28
    name: "Stove Air Sensor"
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"
    device_class: "temperature"
    state_class: "measurement"
