substitutions:
  devicename: stove-sensor
  upper_devicename: Stove-Sensor

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini
  
packages:
  device_base: !include common.yaml

dallas:
   pin: D4
   update_interval: 30s
  
sensor:
  - platform: dallas
    address: 0xF50517A19A43FF28
    name: "Stove Air Sensor"
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"
    device_class: "temperature"
    state_class: "measurement"
