esphome:
  name: trap1
  friendly_name: trap1
  on_boot:
    priority: -100
    then:
      - lambda: |-
          pinMode(4, OUTPUT);         // GPIO4
          digitalWrite(4, 1);         // hold HIGH after boot


esp8266:
  board: esp01
  #board_flash_mode: dio

# Enable Home Assistant API
api:
  encryption:
    key: "oHqM0M9F6bq+1qPwhhoH5U5UNuewHEKdKpZHKKkfcBc="

ota:
  - platform: esphome
    password: "308be2fc05f65878a5f9ea63fcab4c69"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.50.29
    gateway: 192.168.50.1
    subnet: 255.255.255.0
  fast_connect: True

logger:
  level: DEBUG
#  baud_rate: 115200
  baud_rate: 0

binary_sensor:
  - platform: status
    name: Mouse trap 1 Status
  - platform: gpio
    name: Sense
    id: noidea
    pin: GPIO2
    
      
      
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Mouse trap 1 IP Address"

sensor:
  - platform: wifi_signal
    name: Mouse trap 1 WiFi Signal
    update_interval: 300s
  - platform: adc
    pin: A0
    id: batt_v
    name: "Trap Battery V"
    update_interval: 2s
    filters:
      - multiply: 6.3659    # turns ADC pin volts into pack volts
      #- calibrate_linear:
        #- 0.88 -> 5.70   # map ADC pin volts to real pack volts
      - median:
          window_size: 7
          send_every: 3
    unit_of_measurement: "V"
    accuracy_decimals: 2
  - platform: template
    name: "Battery %"
    id: batt_pct
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 10s
    lambda: |-
      const float VFULL  = 6.40;  // set for your chemistry
      const float VEMPTY = 4.60;  // set your cutoff
      float v = id(batt_v).state;
      float pct = (v - VEMPTY) / (VFULL - VEMPTY) * 100.0;
      if (pct < 0) pct = 0;
      if (pct > 100) pct = 100;
      return pct;

output:
  - platform: gpio
    pin: GPIO14
    id: out_g14_d1
  - platform: gpio
    pin: GPIO15
    id: out_g15_d2
  - platform: gpio
    pin: GPIO5
    id: out_g5_d3
  ################
  - platform: gpio
    pin: GPIO0
    id: out_0
  - platform: gpio
    pin: GPIO12
    id: out_12
  - platform: gpio
    id: out_4
    pin:
      number: GPIO4
      mode:
        output: true
        open_drain: true    # <-- KEY: only sinks; otherwise floats (high-Z)
  - platform: esp8266_pwm
    id: hv_pwm
    pin: GPIO13
    frequency: 230.6 Hz          # start point; we’ll sweep this
    min_power: 0.0
    max_power: 1.0

switch:
  - platform: output
    name: "GPIO14 LED D1"
    id: sw_g14
    output: out_g14_d1
  - platform: output
    name: "GPIO15 LED D2"
    id: sw_g15
    output: out_g15_d2
  - platform: output
    name: "GPIO5 LED D3"
    id: sw_g5
    output: out_g5_d3
###########################
  - platform: output
    name: "GPIO12"
    id: sw_g12
    output: out_12
  - platform: output
    name: "GPIO0"
    id: sw_g0
    output: out_0
    restore_mode: ALWAYS_ON
  - platform: output
    name: "GPIO4"
    id: sw_g4
    output: out_4
  - platform: template
    name: "HV PWM Run"
    turn_on_action:
      - output.set_level:
          id: hv_pwm
          level: 28.4%         # ~27.8% duty to start; adjust as needed
    turn_off_action:
      - output.set_level:
          id: hv_pwm
          level: 0.0


  - platform: restart
    name: Mouse trap 1 Restart

# ---- Deep Sleep ----
deep_sleep:
  #run_duration: 60s   # stay awake for 60 seconds
  #sleep_duration: 120s # then sleep for 2 minute

# Optional: blink the LED every second while awake
interval:
  - interval: 2s
    then:
      - switch.toggle: sw_g14

button:
  - platform: template
    name: Sleep
    id: my_button
    on_press:
      - deep_sleep.enter:
   #       id: deep_sleep_1


# Duty control
number:
  - platform: template
    name: "HV PWM Duty %"
    min_value: 0
    max_value: 100
    step: 5
    optimistic: true
    set_action:
      - output.set_level:
          id: hv_pwm
          level: !lambda 'return x / 100.0;'

# Frequency control (runtime) – uses Arduino analogWriteFreq()
  - platform: template
    name: "HV PWM Freq (Hz)"
    min_value: 500
    max_value: 10000
    step: 100
    optimistic: true
    set_action:
      - lambda: 'analogWriteFreq((uint16_t) x);'