esphome:
  name: updater
  friendly_name: updater

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "o2+V6aYcH3EK6jwV6VJu6V9VS0q6MaBVAx0GAIc8+O8="

ota:
  - platform: esphome
    password: "4d1436166b06a558d32aca024ee27f12"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Updater Fallback Hotspot"
    password: "iofBacYUj0K4"

captive_portal:

web_server:
  port: 80

    