# Board: Generic ESP8266 Board (Generic)
# Definition: definitions/boards/generic-esp8266/manifest.yaml
substitutions:
  name: gosund_wp3_1
  friendly_name: Gosund WP3-1

esphome:
  name: wps3-1
  friendly_name: wps3-1

esp8266:
  board: esp01_1m

logger:

api:
  encryption:
    key: "Q4+FAXArrCKgHYNH3l3jyrwGUUvJPOeXBFpGDgwCIuI="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: wps3-1 Fallback Hotspot
    password: "0UrQ3G5QkVNm"

captive_portal:

  
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    id: "${name}_button"
    on_press:
      - switch.toggle: "${name}_relay"
  - platform: status
    name: "${friendly_name} Status"
    id: "${name}_status"

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    id: "${name}_relay"
    pin: GPIO14
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

status_led:
  pin:
    number: GPIO12
    inverted: yes

output:
  - platform: gpio
    pin: GPIO13
    inverted: true
    id: led

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi signal"
    id: "${name}_wifi_signal"
    update_interval: 60s
  - platform: uptime
    name: "${friendly_name} Uptime"
    id: "${name}_uptime"
    update_interval: 60s