################################################################
## Packages / Automations
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.automations: &customize
      package: 'automations'



################################################
## Group
################################################



################################################
## Sensor
################################################

  
  
  
sensor:
  - platform: template
    sensors:
      total_automations_on:
        value_template: >-
          {% for state in states.automation if state.state == 'on' %}
          {% if loop.last %}
          {{ loop.index|int }}
          {% endif %}
          {% endfor %}
      total_automations_off:
        value_template: >-
          {% for state in states.automation if state.state == 'off' %}
          {% if loop.last %}
          {{ loop.index|int }}
          {% endif %}
          {% endfor %}
      total_automations:
        value_template: >-
          {% for state in states.automation %}
          {% if loop.last %}
          {{ loop.index|int }}
          {% endif %}
          {% endfor %}
   
    
# automation:
  # - alias: automaion - Send Message about automations.
  # #  initial_to: False
    # trigger:
      # - platform: template
        # value_template: '{{ states.sensor.total_automations_on.state == states.sensor.total_automations.state }}'
    # action:
      # - service: notify.mobile_app_ryan_iphone
        # data:
           # title: 'All automations are on'
           # message: 'All automations are on {{ states.sensor.total_automations_on.state | int }} of {{ states.sensor.total_automations.state }}'
# #      - service: homeassistant.turn_off
# #        entity_id: light.wink_all_lights
             
    
