################################################################
## Packages / BlueIris
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.blueiris: &customize
      package: 'blueiris'


################################################
## Group
################################################



################################################
## Sensor
################################################

sensor:
  - platform: mqtt
    name: "BlueIris"
    state_topic: "BlueIris/app"    
