################################################################
## Packages / BlueIris
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.blueiris: &customize
      package: 'blueiris'


################################################
## Group
################################################



################################################
## Sensor
################################################
 
mqtt:
  sensor:
    - name: "BlueIris"
      state_topic: "BlueIris/app"   

 