### This file does not get tested by Travis!###

  
sensor:
  - platform: google_geocode
    origin: device_tracker.fry
    name: geocode_ryan
    display_zone: hide
    api_key: !secret google_geocode
  - platform: google_geocode
    origin: device_tracker.chelseas_iphone
    name: geocode_chelsea
    display_zone: hide
    api_key: !secret google_geocode

  # https://github.com/custom-components/sensor.authenticated
  - platform: authenticated
    enable_notification: 'True'
    exclude:
      - 192.168.47.202
      - 192.168.47.90
      - 192.168.49.3
      - 127.0.0.1
      - 172.30.32.2
      
      
  - platform: wundergroundpws
    api_key: !secret wu_secret
    pws_id: KMDWESTM78
    numeric_precision: none
    monitored_conditions:
    #  - humidity
      - temp
      - dewpt
      - heatIndex
      - windChill
      - precipRate
      - precipTotal
    #  - pressure
    #  - windGust
    #  - windSpeed
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n
      - weather_5d
      - weather_5n
      - temp_high_1d
      - temp_low_1d
      - wind_1d
      - precip_1d
      - precip_chance_1d
   #   - winddir
   #   - neighborhood
   #   - obsTimeLocal
   #   - stationID
   #   - elev
      - today_summary

#binary_sensor: 
#  - platform: car_wash
#    weather: weather.home


circadian_lighting:
switch:
  - platform: circadian_lighting
    name: hallway
    lights_rgb:
      - light.wink_hallway
  - platform: circadian_lighting
    name: bedroom
    lights_rgb:
      - light.bed_room_overhead_2_07825c03_level_on_off
      - light.bed_room_overhead_1_0359a396
      - light.bed_room_overhead_3_08385c03_level_on_off
  - platform: circadian_lighting
    name: chicken
    lights_rgb:
      - light.wink_ge_link_bulb
      - light.ge_daylight_b1510014_level_on_off
  - platform: circadian_lighting
    name: bathroom
    lights_rgb:
      - light.wink_led_strip_bath
    
climate:
  - platform: climate_group
    name: 'Climate Upstairs Both'
    temperature_unit: F  # default to celsius, 'C' or 'F'
    entities:
    - climate.craft_room
    - climate.office

