### This file does not get tested by Travis!###

image_processing:
  - platform: deepstack_object
    ip_address: 192.168.47.205
    port: 5000
    save_file_folder: /config/www/deepstack_person_images
    target: 
      - person
      - car
      - truck
      - dog
      - cat
    confidence: 85
    source:
      - entity_id: camera.back_deck
        name: person_detector_bd
      - entity_id: camera.deepstack_test
        name: deepstack_test
      - entity_id: camera.p230
        name: person_detector_side
  - platform: deepstack_object
    ip_address: 192.168.47.205
    port: 5000
    save_file_folder: /config/www/deepstack_person_images
    target: 
      - person
    confidence: 85
    source:
      - entity_id: camera.front_porch
        name: person_detector_fp
  - platform: deepstack_object
    ip_address: 192.168.47.205
    port: 5000
    save_file_folder: /config/www/deepstack_object_images
    target: 
      - person
      - car
      - truck
      - dog
      - cat
    confidence: 80
    source:
      - entity_id: camera.driveway
        name: object_detection_driveway
      - entity_id: camera.p230
        name: object_detection_side
      - entity_id: camera.camz238
        name: object_detection_coop

circadian_lighting:
  
sensor:
  - platform: google_geocode
    origin: device_tracker.fry
    name: geocode_ryan
    display_zone: hide
    api_key: !secret google_geocode
  - platform: google_geocode
    origin: device_tracker.pixel_3
    name: geocode_chelsea
    display_zone: hide
    api_key: !secret google_geocode

  # https://github.com/custom-components/sensor.authenticated
  - platform: authenticated
    enable_notification: 'True'
    exclude:
      - 192.168.47.202
      - 192.168.47.90
      - 192.168.49.3
      - 127.0.0.1
      - 172.30.32.2

  - platform: sun2
    monitored_conditions:
      - sunrise
      - sunset

binary_sensor: 
  - platform: car_wash
    weather: weather.dark_sky

switch:
  - platform: circadian_lighting
    lights_rgb:
      - light.wink_bed_room
      - light.wink_hallway
      - light.wink_led_strip_bed
