################################################################
## Packages / ecobee
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.ecobee: &customize
      package: 'ecobee'


################################################
## ecobee Platform
################################################

#ecobee:
#  api_key: !secret eco_api

 
# notify:
  # - name: ecobee
    # platform: ecobee

  
################################################
## ecobee Inputs
################################################

  
  
input_number:
  fan_min_on_time:
    name: Fan On Time / Hour
    icon: mdi:timer-outline
    initial: 15
    min: 0
    max: 55
    step: 5
    
    
################################################
## ecobee Automation
################################################


automation:
  - alias: "Set Fan On Time"
    trigger:
      platform: state
      entity_id: input_number.fan_min_on_time
    action:
    - service: ecobee.set_fan_min_on_time
      data:
         fan_min_on_time: '{{ states.input_number.fan_min_on_time.state | int }}'
         
