################################################################
## Packages / ecobee
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.ecobee: &customize
      package: 'ecobee'

    packages.ecobee_exposed: &customize_exposed
      <<: *customize
      haaska_hidden: false
      homebridge_hidden: false

    binary_sensor.guest_bedroom_occupancy:
      <<: *customize_exposed
      friendly_name: "Guest Bedroom Occupancy"
      device_class: occupancy

    binary_sensor.home_occupancy:
      <<: *customize_exposed
      friendly_name: "Hallway Occupancy"
      device_class: occupancy

    binary_sensor.living_room_occupancy:
      <<: *customize_exposed
      friendly_name: "Living Room Occupancy"
      device_class: occupancy

    binary_sensor.master_bedroom_occupancy:
      <<: *customize_exposed
      friendly_name: "Master Bedroom Occupancy"
      device_class: occupancy

    climate.wink_home:
      <<: *customize_exposed
      friendly_name: "Home"
      icon: mdi:nest-thermostat

    sensor.guest_bedroom_temperature:
      <<: *customize_exposed
      friendly_name: "Guest Bedroom Temperature"
      icon: mdi:thermometer

    sensor.home_humidity:
      <<: *customize_exposed
      friendly_name: "Home Humidity"
      icon: mdi:water-percent

    sensor.home_temperature:
      <<: *customize_exposed
      friendly_name: "Home Temperature"
      icon: mdi:thermometer

    sensor.living_room_temperature:
      <<: *customize_exposed
      friendly_name: "Living Room Temperature"
      icon: mdi:thermometer

    sensor.master_bedroom_temperature:
      <<: *customize_exposed
      friendly_name: "Master Bedroom Temperature"
      icon: mdi:thermometer

################################################
## ecobee Platform
################################################

ecobee:
  api_key: !secret eco_api
  hold_temp: true
 
notify:
  - name: ecobee
    platform: ecobee

  
################################################
## ecobee Inputs
################################################

  
  
input_number:
  fan_min_on_time:
    name: Fan On Time / Hour
    icon: mdi:timer
    initial: 15
    min: 0
    max: 55
    step: 5
    
    
################################################
## ecobee Automation
################################################


automation:
  - alias: "Set Fan On Time"
    trigger:
      platform: state
      entity_id: input_number.fan_min_on_time
    action:
    - service: climate.ecobee_set_fan_min_on_time
      data_template:
         fan_min_on_time: '{{ states.input_number.fan_min_on_time.state | int }}'
         
