## Packages / Fire Tab
################################################################

################################################
## Customize
################################################


################################################
## Group
################################################

##http://www.ozerov.de/fully-kiosk-browser/


################################################
## Sensor
################################################

light:
  - platform: template
    lights:
      dashboard_screen:
        turn_on:
        turn_off:
        set_level:

# this causes the screen to constantly get set to 255
#switch:
#  - platform: rest
#    resource: !secret fully_switch

binary_sensor:
  - platform: mqtt
    name: dashboard_motion
    state_topic: any/value

sensor:
   - platform: rest
     name: Firetab
     json_attributes:
       - isScreenOn
       - batteryLevel
       - kioskMode
       - screenBrightness
       - motionDetectorState
       - maintenanceMode
#       - appFreeMemory
#       - appUsedMemory
#       - totalFreeMemory
#       - totalUsedMemory
       - hostname4
       - ip4
       - mac
       - startUrl
       - currentPage
       - currentFragment
       - plugged
     resource: !secret fully_url
     value_template: '{{ value_json.screenBrightness }}'
#     scan_interval: 60


################################################
## Notify
################################################    
   
notify:
  - name: Fire_dash
    platform: lannouncer
    host: 192.168.47.163
  - name: fully
    platform: command_line
    command: "/root/.homeassistant/scripts/fully.sh"
    
    