################################################################
## Packages / garage
################################################################

################################################
## Customize
################################################



################################################
## timer Platform
################################################

timer:
  garage_lights:


  
################################################
## basement_light Automation
################################################


automation:
  - alias: "timer - garage lights"
    id: 55f96c79-e01c-4d18-b9d9-3a5693fca323
    trigger:
      platform: event
      event_type:  timer.finished
      event_data:
        entity_id: timer.garage_lights
    action:
    - service: homeassistant.turn_off
      entity_id: light.garage_lights_front