homeassistant:
#  customize:
#    zone.home:
#      beacon:
#        uuid: 48de4980-968d-11e4-b4a9-0800200c9a66
#        major: 1
#        minor: 1116

zone:
  - name: Home
    latitude: 39.444360
    longitude: -76.998732
    radius: 400
    icon: mdi:home
