################################################################
## Packages / IOS
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.ios: &customize
      package: 'ios'
      hidden: true
      haaska_hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true
#      emulated_hue_name: "back office light"

################################################
## Platform
################################################

ios:
  push:
    categories:
      - name: 'camera1'
        identifier: 'camera1'
        actions:
          - identifier: 'CHICKEN_OPEN_DOOR'
            title: 'Open Chicken Door'
            authenticationRequired: yes
          - identifier: 'CHICKEN_CLOSE_DOOR'
            title: 'Close Chicken Door'
            authenticationRequired: yes
      - name: door
        identifier: 'door'
        actions:
          - identifier: 'GARAGE_OPEN_FIRST'
            title: 'Open First'
            authenticationRequired: yes
          - identifier: 'GARAGE_OPEN_SECOND'
            title: 'Open Second'
            authenticationRequired: yes
          - identifier: 'GARAGE_OPEN_THIRD'
            title: 'Open Third'
            authenticationRequired: yes
          - identifier: 'GARAGE_OPEN_ALL'
            title: 'Open All'
            authenticationRequired: yes
            destructive: true
      - name: door_close
        identifier: 'door_close'
        actions:
          - identifier: 'GARAGE_CLOSE_FIRST'
            title: 'Close First'
            authenticationRequired: yes
          - identifier: 'GARAGE_CLOSE_SECOND'
            title: 'Close Second'
            authenticationRequired: yes
          - identifier: 'GARAGE_CLOSE_THIRD'
            title: 'Close Third'
            authenticationRequired: yes
          - identifier: 'GARAGE_CLOSE_ALL'
            title: 'Close All'
            authenticationRequired: yes
            destructive: true
      - name: hot_water
        identifier: 'hot_water'
        actions:
          - identifier: 'TURN_ON_HOT_WATER'
            title: 'Turn On Hot Water'
            authenticationRequired: no
      - name: chicken_door
        identifier: 'chicken_door'
        actions:
          - identifier: 'CHICKEN_OPEN_DOOR'
            title: 'Open Chicken Door'
            authenticationRequired: yes
          - identifier: 'CHICKEN_CLOSE_DOOR'
            title: 'Close Chicken Door'
            authenticationRequired: yes
      - name: test
        identifier: 'camera'
        actions:
          - identifier: 'ALLINONE_TRUE'
            title: 'On/True/Open/Lock'
            authenticationRequired: no
          - identifier: 'ALLINONE_FALSE'
            title: 'Off/False/Close/Unlock'
            authenticationRequired: no
      - name: wink_lights
        identifier: 'wink_lights'
        actions:
          - identifier: 'TURN_OFF_WINK_LIGHTS'
            title: 'Turn off wink lights'
            authenticationRequired: no      
