################################################################
## Packages / Wink
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.wink: &customize
      package: 'sn2'



################################################
## Group
################################################



################################################
## Sensor
################################################

  
  
sensor:
- platform: mqtt  
  state_topic: "home/sensornode2"  
  name: "SN2 Humidity"
  icon: mdi:water-percent
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  
  
- platform: mqtt  
  state_topic: "home/sensornode2"  
  name: "SN2 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  
  
- platform: mqtt  
  state_topic: "home/sensornode2"  
  name: "SN2 PIR"  
  value_template: '{{ value_json.motion }}'  
  
- platform: mqtt  
  state_topic: "home/sensornode2"  
  name: "SN2 Reed"  
  value_template: '{{ value_json.reed }}'
  icon_template: >-
    {% if is_state('sensor.sn2_reed', 'open') %}
       mdi:door-open
    {% else %}
      mdi:door-closed
    {% endif %}
  
- platform: mqtt  
  state_topic: "home/sensornode2"  
  name: "SN2 Temperature"  
  unit_of_measurement: "°F"
  icon: 'mdi:temperature-fahrenheit'
  value_template: '{{ value_json.temperature | round(1) }}'  

- platform: mqtt
  state_topic: "home/sensornode1"
  name: "SN1 Real Feel"
  unit_of_measurement: "?"
  value_template: '{{ value_json.heatIndex | round(1) }}'
   
- platform: mqtt
  state_topic: "home/sensornode2"
  name: "SN2 Real Feel"
  unit_of_measurement: "?"
  value_template: '{{ value_json.heatIndex | round(1) }}'
  
- platform: mqtt  
  state_topic: "home/sensornode2/availability"  
  name: "SN2 Availablilty"  
  payload_available: "online"
  payload_not_available: "offline"

    