################################################################
## Packages / Weather
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.weather: &customize
      package: 'weather'
      haaska_hidden: true
      homebridge_hidden: true
      emulated_hue_hidden: true

    sensor.season:
      <<: *customize
      friendly_name: "Season"
      icon: mdi:weather-snowy-rainy


################################################
## Group
################################################



################################################
## Sensor
################################################

