################################################################
## Packages / Wink
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.wink: &customize
      package: 'wink'
    light.wink_led_strip_bed:
      package: 'wink'
    light.wink_led_strip_tv:
      package: 'wink'
    light.wink_wink_all_lights:
      package: 'wink'
    light.wink_bed_room_2:
      package: 'wink'


################################################
## Group
################################################



################################################
## Sensor
################################################

wink:
  email: !secret wink_user
  password: !secret wink_pass
  client_id: !secret wink_client
  client_secret: !secret wink_secret
  local_control: True
  
  
  
sensor:
  - platform: wink
    entity_namespace: wink

  - platform: template
    sensors:
      total_wink_lights_on:
        entity_id: group.all_lights
        value_template: >-
          {% for state in states.light if state.state == 'on' and "wink" in state.entity_id and "strip" not in state.entity_id and "wink_wink" not in state.entity_id %}
          {% if loop.last %}
          {{ loop.index|int }}
          {% endif %}
          {% endfor %}
      total_wink_lights_off:
        entity_id: group.all_lights
        value_template: >-
          {% for state in states.light if state.state == 'off' and "wink" in state.entity_id and "strip" not in state.entity_id and "wink_wink" not in state.entity_id %}
          {% if loop.last %}
          {{ loop.index|int }}
          {% endif %}
          {% endfor %}
      total_wink_lights:
        entity_id: group.all_lights
        value_template: >-
          {% for state in states.light if state.state != 'unavailable' and "wink" in state.entity_id and "strip" not in state.entity_id and "wink_wink" not in state.entity_id %}
          {% if loop.last %}
          {{ loop.index|int }}
          {% endif %}
          {% endfor %}

light:
  - platform: wink
    entity_namespace: wink

switch:
  - platform: wink
    entity_namespace: wink

binary_sensor:
  - platform: wink
    entity_namespace: wink

cover:
  - platform: wink
    entity_namespace: wink

climate:
  - platform: wink
    entity_namespace: wink

scene:
  - platform: wink
    entity_namespace: wink

    
    
automation:
  - alias: wink - Send Message when all the wink lights are on.
  #  initial_to: False
    trigger:
      - platform: template
        value_template: '{{ states.sensor.total_wink_lights_on.state == states.sensor.total_wink_lights.state }}'
    action:
      - service: notify.ios_ryans_iphone_app2
        data_template:
           title: 'All wink lights are on'
           message: 'All the wink lights are on {{ states.sensor.total_wink_lights_on.state | int }} of {{ states.sensor.total_wink_lights.state }}'
           data:
             push:
               category: 'wink_lights'
#      - service: homeassistant.turn_off
#        entity_id: light.wink_all_lights
             
  - alias: IOS - Wink Lights
    trigger:
      platform: event
      event_type: ios.notification_action_fired
    condition:
     condition: template
     value_template: "{{(trigger.event.data.actionName == 'TURN_OFF_WINK_LIGHTS')}}"
    action:
      service: homeassistant.turn_off
      entity_id: light.wink_wink_all_lights
    
